<?php
/**
 * Copyright (c) 2018-2021 David J Bullock
 * Web Power and Light
*/

 if (! defined( 'ABSPATH' ) ) { die(); }  if (class_exists('m4ac_c6rqypiacz4') ) { 
class m4ac_nkjcf17dwe_ { public $slug = 'divi';  public $script_version = '1.0.7';  public $to_json = [];  public $omitted_blocks = [];  public $ns = '';  public $prefix = '';  public $I18n = '';  public $access_class;  private 
function __construct(){} static 
function m4ac_zw_dhmca() : self { static $m4ac_u4tpxcro19 = null; if(is_null($m4ac_u4tpxcro19)){ $m4ac_u4tpxcro19 = new self; $m4ac_u4tpxcro19->access_class = m4ac_rntik2rdq0::m4ac_zw_dhmca(); $m4ac_u4tpxcro19->prefix = $m4ac_u4tpxcro19->access_class::PREFIX; $m4ac_u4tpxcro19->ns = $m4ac_u4tpxcro19->access_class::NS; } return $m4ac_u4tpxcro19; } 
function m4ac_w07mrqh2sxlp() { add_filter("{$this->ns}/{$this->slug}/control/config", [$this, 'm4ac_xi01vne9ho3u'], 10, 1); $m4ac_n_j31z9qsv = $this->access_class->m4ac_hrc7dpu9j(); $this->I18n = $m4ac_n_j31z9qsv->m4ac_up3uovdq_ib7( false, $this->slug ); $this->to_json['WPAL_BLOCKS_SETTINGS_TITLE'] = $this->I18n['settings_title']; $this->to_json['WPAL_BLOCKS_PREFIX'] = $this->prefix; $this->to_json['WPAL_BLOCKS_KEYS_REMOVED_TEXT'] = $this->I18n['keys_removed_text']; $this->to_json['tags'] = $m4ac_n_j31z9qsv->m4ac_ni3dn9fc();  $this->to_json['controls'] = $m4ac_n_j31z9qsv->m4ac_buapm02l_8dx($this->slug);   $this->omitted_blocks = apply_filters("{$this->ns}/{$this->slug}/settings/omitted_blocks", ['et_pb_column', 'et_pb_column_inner']);  add_action('et_builder_ready', [$this, 'm4ac_eqrthp60u19o'], 9999 );  add_action(is_admin() ? 'admin_enqueue_scripts' : 'wp_enqueue_scripts', [$this, 'm4ac_cihcgvtj'], 9999); }  
function m4ac_eqrthp60u19o(){ global $shortcode_tags; $m4ac_mkenioshjy = []; foreach ($shortcode_tags as $m4ac_o75qrnlisk => $m4ac__ijlyd9ens) { if ( is_array($m4ac__ijlyd9ens) ) { if ( $m4ac__ijlyd9ens[0] instanceof ET_Builder_Element || $m4ac__ijlyd9ens[0] instanceof ET_Builder_Module ) { $m4ac_mkenioshjy[$m4ac_o75qrnlisk] = $m4ac__ijlyd9ens; remove_shortcode($m4ac_o75qrnlisk, $m4ac__ijlyd9ens); } } } if ( !empty($m4ac_mkenioshjy) ){ foreach ( $m4ac_mkenioshjy as $m4ac_o75qrnlisk => $m4ac__ijlyd9ens ) { $m4ac_o592unb1gm8 = $m4ac__ijlyd9ens[0]; $m4ac_yl2zctsag = $m4ac__ijlyd9ens[1]; $m4ac_o592unb1gm8->settings_modal_toggles['custom_css']['toggles']['wpal-blocks'] = ['title' => $this->I18n['settings_title'], 'priority' => 100]; if ( !isset($m4ac_o592unb1gm8->fields_unprocessed["{$this->prefix}_anymembership"] ) ){ $m4ac_se0rlu1358j = in_array($m4ac_o75qrnlisk, $this->omitted_blocks) ? [] : $this->to_json['controls']; if ( is_array($m4ac_se0rlu1358j) && !empty($m4ac_se0rlu1358j) ){ $m4ac_o592unb1gm8->fields_unprocessed = array_merge($m4ac_o592unb1gm8->fields_unprocessed, $m4ac_se0rlu1358j); } } add_shortcode( $m4ac_o75qrnlisk, function($m4ac_c1m92xtgl8z, $m4ac_c4qc56391fd, $m4ac_qxcoswr2p9_y) use ($m4ac_o592unb1gm8, $m4ac_yl2zctsag) { return $m4ac_o592unb1gm8->$m4ac_yl2zctsag( $m4ac_c1m92xtgl8z, $m4ac_c4qc56391fd, $m4ac_qxcoswr2p9_y ); }); } } }  
function m4ac_xi01vne9ho3u( array $m4ac_b7_c3kyi ) : array { $m4ac_v1ths6xqe = []; if ( is_array($m4ac_b7_c3kyi) && !empty($m4ac_b7_c3kyi) ){ foreach( $m4ac_b7_c3kyi as $m4ac_gduhckfg => $m4ac_wc9s2dnt4y ) { $m4ac_ss6bwxopg8 = !empty($m4ac_wc9s2dnt4y['type']) ? $m4ac_wc9s2dnt4y['type'] : false; $m4ac_pzocy3nw = !empty($m4ac_wc9s2dnt4y['name']) ? $m4ac_wc9s2dnt4y['name'] : false; $m4ac_e2dzp_h0 = !empty($m4ac_wc9s2dnt4y['description']) ? $m4ac_wc9s2dnt4y['description'] : false; $m4ac_jti0_6zv = !empty($m4ac_wc9s2dnt4y['sanitize']) ? $m4ac_wc9s2dnt4y['sanitize'] : false; if ( $m4ac_ss6bwxopg8 && $m4ac_pzocy3nw ){ switch ($m4ac_ss6bwxopg8) { case 'checkbox': $m4ac_v1ths6xqe[$m4ac_pzocy3nw] = [ 'wpald' => 'toggle', 'wpald_level' => !empty($m4ac_wc9s2dnt4y['level']) ? $m4ac_wc9s2dnt4y['level'] : '', 'wpald_toggles' => isset($m4ac_wc9s2dnt4y['toggles']) && is_array($m4ac_wc9s2dnt4y['toggles']) ? $m4ac_wc9s2dnt4y['toggles'] : false, 'type' => 'yes_no_button', 'label' => $m4ac_wc9s2dnt4y['label'], 'options' => [ 'off' => !empty($m4ac_wc9s2dnt4y['label_off']) ? $m4ac_wc9s2dnt4y['label_off'] : _x( 'Off', 'divi', $this->ns), 'on' => !empty($m4ac_wc9s2dnt4y['label_on']) ? $m4ac_wc9s2dnt4y['label_on'] : _x('On', 'divi', $this->ns) ], 'default' => ( isset($m4ac_wc9s2dnt4y['default']) && (int) $m4ac_wc9s2dnt4y['default'] > 0 ) ? 'on' : 'off' ]; break; case 'textarea': $m4ac_v1ths6xqe[$m4ac_pzocy3nw] = [ 'wpald' => 'textarea', 'type' => 'text', 'label' => $m4ac_wc9s2dnt4y['label'], 'default' => '' ]; break; case 'text': $m4ac_v1ths6xqe[$m4ac_pzocy3nw] = [ 'wpald' => 'text', 'type' => 'text', 'label' => $m4ac_wc9s2dnt4y['label'], 'default' => '' ]; break; case 'SELECT2': $m4ac_v1ths6xqe[$m4ac_pzocy3nw] = [ 'wpald' => 'select2', 'type' => 'text', 'label' => $m4ac_wc9s2dnt4y['label'] ]; break; default: break; } if ( $m4ac_e2dzp_h0 ){ $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['description'] = $m4ac_e2dzp_h0; } if ( $m4ac_jti0_6zv ){ $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['sanitize'] = $m4ac_jti0_6zv; } $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['additional_att'] = !empty($m4ac_wc9s2dnt4y['additional_att']) ? $m4ac_wc9s2dnt4y['additional_att'] : $m4ac_pzocy3nw; $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['option_category'] = !empty($m4ac_wc9s2dnt4y['option_category']) ? $m4ac_wc9s2dnt4y['option_category'] : 'configuration'; $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['tab_slug'] = !empty($m4ac_wc9s2dnt4y['tab_slug']) ? $m4ac_wc9s2dnt4y['tab_slug'] : 'custom_css'; $m4ac_v1ths6xqe[$m4ac_pzocy3nw]['toggle_slug'] = !empty($m4ac_wc9s2dnt4y['toggle_slug']) ? $m4ac_wc9s2dnt4y['toggle_slug'] : 'wpal-blocks'; } } } return $m4ac_v1ths6xqe; }  
function m4ac_cihcgvtj(){ $m4ac_kkq24nui = 'wpal-blocks-divi-editor'; $this->access_class->m4ac_hrc7dpu9j()->m4ac_nu6elf21_mzn( false, $m4ac_kkq24nui ); wp_register_style('select2css_divi', plugin_dir_url(__FILE__) . 'select2_divi.css', false, $this->script_version, 'all'); wp_register_script("{$m4ac_kkq24nui}_main", plugin_dir_url(__FILE__) . 'editor.js', ['jquery'], $this->script_version, true); wp_enqueue_style('select2css_divi'); wp_enqueue_script("{$m4ac_kkq24nui}_s2js"); wp_enqueue_script("{$m4ac_kkq24nui}_main"); wp_localize_script("{$m4ac_kkq24nui}_main", 'wpald_params', $this->to_json); } } }
