<?php
/**
 * Copyright (c) 2020 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_iqsra0infl { static 
function m4ac_jok54t10_7d() { self::m4ac_r8puy4_xrs6(); self::m4ac_eqo0b3f8plk(); self::m4ac_ft1vp8sfinr(); self::m4ac_uy5uz4ko3ns(); self::m4ac_k9qz4sx605c(); self::m4ac__hb0ujx1yd9e(); self::m4ac_p19qusri(); self::m4ac_s4s97pvwxc(); self::m4ac_cglp25ec_3ax(); self::m4ac_yhwbc4zx8a0();  self::m4ac_ozw4raext_qb(); self::m4ac_uzbju40pcv(); self::m4ac_z8g6f9zvhl7(); self::m4ac_xs51irq9kavj(); self::m4ac_zmostcn3ykfa(); self::m4ac_cgul_sex0nk(); self::m4ac_qp1othu8(); self::m4ac_sq8sv_bg(); self::m4ac_jmkd2rfnh071(); self::m4ac_p03dftwk(); } private static 
function m4ac_k9qz4sx605c() { echo '<h3>Object Caching</h3>'; echo '<div class="indented">'; if (wp_using_ext_object_cache() ) { global $wp_object_cache; if (method_exists($wp_object_cache, 'stats')) { echo $wp_object_cache->stats(); } else { echo '<p>Object Cache Data unavailable</p>'; } } else { echo '<p style="color:red;"><em><strong>Missing</strong></em></p>'; } echo '</div>'; } private static 
function m4ac_eqo0b3f8plk() { $m4ac_ks5fpk_lrjmz = [ 'HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'CF-CONNECTING-IP', ]; echo '<h3>Remote IP Address</h3>'; echo '<div class="indented">'; foreach($m4ac_ks5fpk_lrjmz as $m4ac_v2h87nftp) { if (! empty($_SERVER[$m4ac_v2h87nftp])) { echo $m4ac_v2h87nftp, ' - ', $_SERVER[$m4ac_v2h87nftp], '<br />'; } } echo '</div>'; } private static 
function m4ac_s4s97pvwxc() { global $wpdb; $m4ac_kqzvwpxl7 = get_option('activememberium_tables', [] ); $m4ac_ix2ahcuv = []; if (is_array($m4ac_kqzvwpxl7)) { foreach($m4ac_kqzvwpxl7 as $m4ac_ixesh4rzk) { $m4ac_xtcz6bi97flk = "SELECT 1 FROM `{$m4ac_ixesh4rzk}` LIMIT 1;"; $wpdb->get_var($m4ac_xtcz6bi97flk); $m4ac_vykuqfwdj_0 = $wpdb->last_error; if ($m4ac_vykuqfwdj_0) { $m4ac_ix2ahcuv[] = "Table '{$m4ac_ixesh4rzk}' : <span style='font-weight:bold;color:red;'>{$m4ac_vykuqfwdj_0}</span><br />"; } } } echo '<h3>Missing Database Tables</h3>'; echo '<div class="indented">'; if (! empty($m4ac_ix2ahcuv)) { foreach($m4ac_ix2ahcuv as $m4ac_ho5flzpr3a) { echo $m4ac_ho5flzpr3a, '<br>'; } } else { echo '<p>None</p>'; } echo '</div>'; } private static 
function m4ac_f7qsi4dwogep() { $m4ac_hcmfbhk0ejsg = '<strong style="color:red;">Unknown</strong>'; if (is_file('/proc/cpuinfo') ) { $cpuinfo = file('/proc/cpuinfo'); foreach($cpuinfo as $line) { if (substr($line, 0, 9) == 'cpu cores') { $m4ac_hcmfbhk0ejsg = intval($m4ac_hcmfbhk0ejsg) + (int) substr($line, strpos($line, ':') + 1); } } } return $m4ac_hcmfbhk0ejsg; } private static 
function m4ac_ft1vp8sfinr() { $m4ac_xf28u9sh03ev = memberium_app()->m4ac__59c71kr(); echo '<h3>Third Party Extensions Loaded for Memberium</h3>'; echo '<div class="indented">'; if (! empty($m4ac_xf28u9sh03ev)) { foreach($m4ac_xf28u9sh03ev as $m4ac_q5u6fln0c3) { echo "<p>{$m4ac_q5u6fln0c3['name']}</p>"; } } else { echo '<p>None</p>'; } echo '</div>'; } private static 
function m4ac_yhwbc4zx8a0() { echo '<h3>Network</h3>'; echo '<div class="indented">'; $m4ac_ygjqnpcx = [ 'licenseserver.webpowerandlight.com', ]; echo '<h3>License Servers</h3>'; echo '<div class="indented">'; $m4ac_l0enw_2go = false; foreach ($m4ac_ygjqnpcx as $m4ac_ak_b81p6) { $m4ac_iur0o3zyt = gethostbyname($m4ac_ak_b81p6); if ($m4ac_ak_b81p6 == $m4ac_iur0o3zyt) { $m4ac_iur0o3zyt ='<span style="color:red;">Failed To Resolve</span>'; $m4ac_l0enw_2go = true; } else { $m4ac_iur0o3zyt ='<span style="color:green;">' . $m4ac_iur0o3zyt . '</span>'; } echo '<p>', $m4ac_ak_b81p6, ' resolves to <strong>', $m4ac_iur0o3zyt, '</strong></p>'; } if ($m4ac_l0enw_2go) { echo '<p style="color:red;">One or more hostnames failed to resolve due to DNS issues.</p>'; } $m4ac_kx_kwy1ig = [ 'https://licenseserver.webpowerandlight.com/getlicense.php', 'https://licenseserver.webpowerandlight.com/memberium-is/current-version.php', ]; $m4ac_l0enw_2go = false; foreach ($m4ac_kx_kwy1ig as $m4ac_atr94xdeg3) { $m4ac_fic2e07vfkz = wp_remote_get($m4ac_atr94xdeg3); if (is_array($m4ac_fic2e07vfkz) ) { } else { echo '<p>', $m4ac_fic2e07vfkz->errors['http_request_failed'][0], '</p>'; $m4ac_l0enw_2go = true; } } if (! $m4ac_l0enw_2go) { echo '<p><strong style="color:green;">Connection Successful</strong></p>'; } unset($m4ac_iur0o3zyt, $m4ac_l0enw_2go, $m4ac_ak_b81p6, $m4ac_ygjqnpcx); echo '</div>'; } private static 
function m4ac__hb0ujx1yd9e() { echo '<h3>System Load</h3>'; echo '<div class="indented">'; if (function_exists('sys_getloadavg') ) { $m4ac_yu08tsjqe4ki = sys_getloadavg(); echo '<strong>Last Minute</strong>:  ', $m4ac_yu08tsjqe4ki[0], '<br>'; echo '<strong>Last 5 Minutes</strong>:  ', $m4ac_yu08tsjqe4ki[1], '<br>'; echo '<strong>Last 15 Minutes</strong>:  ', $m4ac_yu08tsjqe4ki[2], '<br>'; } else { echo '<p style="font-weight:bold;color:red;">Operating System missing Load Average Reports.</p>'; } echo '</div>'; echo '<p></p>'; } private static 
function m4ac_r8puy4_xrs6() { global $wpdb; $m4ac_hcmfbhk0ejsg = self::m4ac_f7qsi4dwogep(); $m4ac_vw37ualdet = php_uname('m'); $m4ac_sy2zc15rsqie = $wpdb->db_version(); $m4ac_jgniouf_v = php_uname('n'); $m4ac_g1aetkjzdf = php_uname('s'); $m4ac_eswyrh71z5k = php_uname('v'); $m4ac_obyh_d769 = phpversion(); $m4ac_ng15md8xfor3 = php_sapi_name(); $m4ac_kmq95a1exf2 = isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : '<strong style="color:red;">Unknown</strong>'; $m4ac_fheyfujga6 = get_current_user(); $m4ac_tarbxn6m = memberium_app()->m4ac_cbc5pz_ng4(); echo '<h3>System Info</h3>'; echo '<div class="indented">'; echo "<strong>Hostname</strong>:  {$m4ac_jgniouf_v}<br>"; echo "<strong>CPU Type</strong>:  {$m4ac_vw37ualdet}<br>"; echo "<strong>CPU Cores</strong>:  {$m4ac_hcmfbhk0ejsg}<br>"; echo "<strong>Operating System</strong>:  {$m4ac_g1aetkjzdf}<br>"; echo "<strong>Web Server Type</strong>:  {$m4ac_kmq95a1exf2}<br>"; echo "<strong>Username</strong>:  {$m4ac_fheyfujga6}<br>"; echo "<strong>SAPI</strong>:  {$m4ac_ng15md8xfor3}<br>"; echo "<strong>PHP Version</strong>:  {$m4ac_obyh_d769}<br>"; echo "<strong>WordPress Version</strong>:  {$m4ac_tarbxn6m}<br>"; echo "<strong>Database Version</strong>:  {$m4ac_sy2zc15rsqie}<br>"; echo '<p></p>'; echo '<strong>Home Path</strong>:  ', get_home_path(), '<br>'; echo '<strong>Install Point</strong>: ', dirname(MEMBERIUM_HOME), '<br>'; echo '<p></p>'; echo '</div>'; } private static 
function m4ac_uy5uz4ko3ns() { echo '<h3>PHP Modules Loaded</h3>'; echo '<div class="indented">'; echo '<div style="width:600px;">', implode(', ', get_loaded_extensions() ), '</div>'; echo '</div>'; } private static 
function m4ac_p19qusri() { global $wpdb; echo '<h3>MySQL Configuration</h3>'; echo '<div class="indented">'; echo '<h3>Database Storage Engines:</h3>'; echo '<table>'; echo '<tr>'; echo '<td>Engine Name</td>'; echo '<td>Support</td>'; echo '<td>Comments / Description</td>'; echo '</tr>'; $m4ac_xtcz6bi97flk = 'SHOW STORAGE ENGINES;'; $m4ac_f92tkhgnzfcb = $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); foreach($m4ac_f92tkhgnzfcb as $m4ac_fic2e07vfkz) { echo '<tr>'; echo '<td>',$m4ac_fic2e07vfkz['Engine'],'</td>'; echo '<td>',$m4ac_fic2e07vfkz['Support'],'</td>'; echo '<td>',$m4ac_fic2e07vfkz['Comment'],'</td>'; echo '</tr>'; } $m4ac_xtcz6bi97flk = "show variables like 'have_query_cache';"; $m4ac_f92tkhgnzfcb = $wpdb->get_results($m4ac_xtcz6bi97flk); echo '</table>'; echo '<h3>Cache Configuration</h3>'; echo '<strong>', $m4ac_f92tkhgnzfcb[0]->Variable_name, '</strong> = ', $m4ac_f92tkhgnzfcb[0]->Value, '<br>'; $m4ac_xtcz6bi97flk = "show variables like '%query%';"; $m4ac_f92tkhgnzfcb = $wpdb->get_results($m4ac_xtcz6bi97flk); foreach($m4ac_f92tkhgnzfcb as $m4ac_fic2e07vfkz) { echo '<strong>', $m4ac_fic2e07vfkz->Variable_name, '</strong> = ', $m4ac_fic2e07vfkz->Value, '<br>'; } echo '</div>'; }  static 
function m4ac_zmostcn3ykfa() { echo '<h3>wp-config.php:</h3>'; if (file_exists(get_home_path() . 'wp-config.php') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . 'wp-config.php'), '</textarea>'; } } static 
function m4ac_ozw4raext_qb() { echo '<h3>.htaccess</h3>'; if (file_exists(get_home_path() . '.htaccess') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . '.htaccess'), '</textarea>'; } } static 
function m4ac_cglp25ec_3ax() { echo '<h3>CURL Library Support</h3>'; echo '<div class="indented">'; if (function_exists('curl_version') ) { $m4ac_n910gf5o6xv = curl_version(); echo '<strong>Version</strong>: ', $m4ac_n910gf5o6xv['version'], '<br />'; echo '<strong>Version Number</strong>: ', $m4ac_n910gf5o6xv['version_number'], '<br />'; echo '<strong>SSL Version</strong>: ', $m4ac_n910gf5o6xv['ssl_version'], '<br />'; echo '<strong>LibZ Version</strong>: ', $m4ac_n910gf5o6xv['libz_version'], '<br />'; echo '<strong>Age</strong>: ', $m4ac_n910gf5o6xv['age'], '<br />'; } else { echo '<p style="color:red;font-weight:bold;">CURL Library Support Missing</p>'; } echo '</div>'; } static 
function m4ac_jmkd2rfnh071() { echo '<h3>Debug Log:</h3>'; if (file_exists(MEMBERIUM_DEBUGLOG) ) { $m4ac_lbqvk60d5 = (0 - min(filesize(MEMBERIUM_DEBUGLOG), MB_IN_BYTES) ); echo '<form method="post" action=""><input type="submit" name="delete-debug" value="Delete Debug Log"></form>'; echo '<textarea readonly=readonly cols="100" rows="20">', file_get_contents(MEMBERIUM_DEBUGLOG, null, null, $m4ac_lbqvk60d5), '</textarea>'; } else { echo '<p style="color:red;font-weight:bold;">No debug log found.</p>'; } } static 
function m4ac_qp1othu8() { $m4ac_qo72gkq534c = get_defined_constants(true); if (isset($m4ac_qo72gkq534c['user']) ) { ksort($m4ac_qo72gkq534c['user']); echo '<h3>Constants</h3>'; echo '<table>'; foreach($m4ac_qo72gkq534c['user'] as $k => $v) { if (is_array($v) ) { echo '<tr><td>', $k, '</td><td>', serialize($v), '</td></tr>'; } else { echo '<tr><td>', $k, '</td><td>', $v, '</td></tr>'; } } echo '</table>'; } } static 
function m4ac_sq8sv_bg() { if (isset($_SERVER) && is_array($_SERVER) ) { $m4ac_kmq95a1exf2 = $_SERVER; ksort($m4ac_kmq95a1exf2); echo '<h3>Server Values</h3>'; echo '<table>'; foreach($m4ac_kmq95a1exf2 as $m4ac_egl6dkai => $m4ac_y2mw1xc6rq) { echo '<tr><td>', $m4ac_egl6dkai, '</td><td>', $m4ac_y2mw1xc6rq, '</td></tr>'; } echo '</table>'; } } static 
function m4ac_xs51irq9kavj() { echo '<h3>wp-admin php.ini</h3>'; if (file_exists(get_home_path() . '/wp-admin/php.ini') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . '/wp-admin/php.ini'), '</textarea>'; } else { echo '<p>Not Found</p>'; } } static 
function m4ac_z8g6f9zvhl7() { echo '<h3>Main php.ini</h3>'; if (file_exists(get_home_path() . 'php.ini') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . 'php.ini'), '</textarea>'; } else { echo '<p>Not Found</p>'; } } static 
function m4ac_uzbju40pcv() { $m4ac_z849ifdt1w = ini_get_all(); if (! empty($m4ac_z849ifdt1w) ) { ksort($m4ac_z849ifdt1w); echo '<h3>PHP .ini Settings</h3>'; echo '<table>'; foreach($m4ac_z849ifdt1w as $m4ac_egl6dkai => $m4ac_y2mw1xc6rq) { if (! empty($m4ac_y2mw1xc6rq['local_value']) || ! empty($m4ac_y2mw1xc6rq['global_value']) ) { echo '<tr><td>', $m4ac_egl6dkai, '</td><td>', isset($m4ac_y2mw1xc6rq['local_value']) ? $m4ac_y2mw1xc6rq['local_value'] : $m4ac_y2mw1xc6rq['global_value'], '</td></tr>'; } } echo '</table>'; } } static 
function m4ac_p03dftwk() { $m4ac_q7wsjnfa = ini_get('error_log'); if (! empty($m4ac_q7wsjnfa) && file_exists($m4ac_q7wsjnfa) ) { $m4ac_cnfeskd714 = (int) filesize($m4ac_q7wsjnfa); $m4ac_u6qfzh5l = MB_IN_BYTES; $m4ac_a0_ngly9c = ($m4ac_cnfeskd714 > $m4ac_u6qfzh5l) ? $m4ac_cnfeskd714 - $m4ac_u6qfzh5l : 0; echo '<h3>PHP Error Log:</h3>'; echo '<textarea readonly=readonly cols="100" rows="20">', file_get_contents($m4ac_q7wsjnfa, null, null, $m4ac_a0_ngly9c), '</textarea>'; } } static 
function m4ac_cgul_sex0nk() { echo '<h3>Cron Jobs</h3>'; echo '<div class="indented">'; $m4ac_e6rbs5f19d4l = []; $m4ac_m_a0fron9m = get_option('cron', [] ); if (count($m4ac_m_a0fron9m) ) { foreach ($m4ac_m_a0fron9m as $m4ac_g085lq2v9 => $m4ac_kx45sgz6) { if (is_array($m4ac_kx45sgz6) ) { foreach ($m4ac_kx45sgz6 as $m4ac_f7sq5rkdew3p => $m4ac_qtfecgz70jy) { if (stripos($m4ac_f7sq5rkdew3p, 'memberium') === 0) { $m4ac_e6rbs5f19d4l[$m4ac_f7sq5rkdew3p] = $m4ac_g085lq2v9; } } } } } echo '<strong style="margin-left:20px;display:inline-block;width:250px;">Cron Job Name</strong><strong>Next Run Time</strong><br>'; if (! empty($m4ac_e6rbs5f19d4l) ) { foreach ($m4ac_e6rbs5f19d4l as $m4ac_pzocy3nw => $m4ac__ndczilub) { echo '<span style="margin-left:20px;display:inline-block;width:250px;">', $m4ac_pzocy3nw, '</span>', date("Y-m-d h:i:s", $m4ac__ndczilub), '<br>'; } } echo '</div>'; }  static 
function m4ac_c6ekr0ag($core) { echo '<h3>CRM Setup</h3>'; echo '<table>'; $m4ac_q2qpk4t0ahj = microtime(true); $m4ac_jkcodjzp = get_object_vars(memberium_app()->m4ac_yiqu4k3xj5()->api('account/view') ); $m4ac_rxbyroz86g4 = microtime(true); $m4ac_h6elwufj = round($m4ac_rxbyroz86g4 - $m4ac_q2qpk4t0ahj, 4); foreach($m4ac_jkcodjzp as $m4ac_egl6dkai => $m4ac_y2mw1xc6rq) { echo '<tr>'; echo '<td style="width:150px;">', ucwords($m4ac_egl6dkai), '</td>'; echo '<td>', $m4ac_y2mw1xc6rq, '</td>'; echo '</tr>'; } echo '</table>'; echo "<p>API Call Duration:  {$m4ac_h6elwufj} seconds</p>"; } static 
function m4ac_ne68obzjq() { global $wpdb; echo '<h3>Cached ActiveCampaign Lists:</h3>';  $m4ac_xtcz6bi97flk = "SELECT `id`, `name` FROM `" . MEMBERIUM_DB_LISTS . "` WHERE appname = %s ORDER BY `id` ASC;"; $m4ac_xtcz6bi97flk = $wpdb->prepare($m4ac_xtcz6bi97flk, memberium_app()->m4ac_bztk3xj1() ); $m4ac_x_1sx47rpefc = $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); if (! empty($m4ac_x_1sx47rpefc) && is_array($m4ac_x_1sx47rpefc) ) { echo '<table>'; echo '<tr><td>List Id</td><td>List Name</td></tr>'; foreach($m4ac_x_1sx47rpefc as $m4ac_lsxa90fgqk) { echo '<tr>'; echo '<td>', $m4ac_lsxa90fgqk['id'], '</td>'; echo '<td>', $m4ac_lsxa90fgqk['name'], '</td>'; echo '</tr>'; } echo '</table>'; } } static 
function m4ac_ivqhu3i94px($m4ac_d2s9mi0r4) { $m4ac_z_6opwls0e7 = m4ac_tl5skz6cfptr::m4ac_a9x5p_oeaqu1(); echo '<h3>License Status</h3>'; echo '<p class="indented">'; echo '<label>Valid</label>'; echo '<span>', ( (boolean) $m4ac_z_6opwls0e7['valid'] ? '<strong style="color:green;">Yes</strong>' : '<strong style="color:red;">No</strong>'), '</span><br />'; if ( (boolean) $m4ac_z_6opwls0e7['trial_mode']) { echo '<label>Trial Mode</label>'; echo '<span><strong style="color:red;">TRIAL LICENSE MODE</strong></span><br />'; } echo '<label>Next Check</label>'; echo '<span>', date('F jS, Y @ h:i:s', $m4ac_z_6opwls0e7['next_check']), '</span><br />'; echo '<label>Renewal Date</label>'; echo '<span>', date('F jS, Y @ h:i:s', $m4ac_z_6opwls0e7['renewal_date']), '</span><br />'; echo '</p>'; echo '<hr />'; echo '<p>Install Point: ', dirname(MEMBERIUM_HOME), '</p>'; echo '<hr />'; echo 'Document Root:  ', get_home_path(), '<hr>'; echo '<h3>License Detail</h3>'; echo '<textarea readonly=readonly cols="100" rows="10">'; foreach ($m4ac_z_6opwls0e7 as $m4ac_egl6dkai => $m4ac_y2mw1xc6rq) { echo ucwords(str_replace('_', ' ', $m4ac_egl6dkai) ), ':  ', $m4ac_y2mw1xc6rq, "\n"; } echo '</textarea>'; } static 
function m4ac_icvyud376xaz() { echo '<h3>Memberships</h3>'; echo '<textarea readonly=readonly cols="100" rows="20">', json_encode(get_option(MEMBERIUM_MEMBERSHIP_SETTINGS, [] ), JSON_PRETTY_PRINT), '</textarea>'; } static 
function m4ac_axb53npk($m4ac_d2s9mi0r4) { $m4ac_lqg2ejwks8 = json_encode( memberium_app()->m4ac_x280qrz9kmic(), JSON_PRETTY_PRINT ); echo '<h3>Settings</h3>'; echo '<textarea readonly=readonly cols="100" rows="20">', $m4ac_lqg2ejwks8, '</textarea>'; } static 
function m4ac_i7mh6laz8_9() { }  } }
