<?php
/**
 * Copyright (c) 2017-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_eghsod68x { static 
function m4ac_hozfsg3t( array $m4ac_ah90o86m, $m4ac_h0_p7cxt = '' ) : int { global $wpdb; $m4ac_wdl2r3x6jg = [ 'contact_id' => memberium_app()->m4ac_w8ohueyv(), 'ipaddress' => m4ac_p58mfx3cua::m4ac_teq1zlwih6(), 'override' => false, 'type' => 'event', 'user_id' => get_current_user_id(), ]; $m4ac_ah90o86m = wp_parse_args( $m4ac_ah90o86m, $m4ac_wdl2r3x6jg ); if ( $m4ac_ah90o86m['type'] == 'webhook' ) { if ( ! memberium_app()->m4ac_x280qrz9kmic( 'event_log_webhooks' ) ) { return 0; } } $m4ac_dkyr51hqv67 = date_default_timezone_get(); date_default_timezone_set( 'UTC' ); $m4ac_uqmdon7p0fek = date( 'Y-m-d H:i:s' ); date_default_timezone_set( $m4ac_dkyr51hqv67 ); $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_md7c8zsu2o = [ 'contactid' => (int) $m4ac_ah90o86m['contact_id'], 'userid' => (int) $m4ac_ah90o86m['user_id'], 'type' => trim($m4ac_ah90o86m['type']), 'appname' => memberium_app()->m4ac_bztk3xj1(), 'ipaddress' => $m4ac_ah90o86m['ipaddress'], 'log' => trim($m4ac_h0_p7cxt) . "\n", 'time' => $m4ac_uqmdon7p0fek, ]; $m4ac_o2lhyvkaf_ = [ '%d', '%d', '%s', '%s', '%s', '%s', '%s', ]; $result = $wpdb->insert($m4ac_jouqjei9gbc3, $m4ac_md7c8zsu2o, $m4ac_o2lhyvkaf_); return (int) $wpdb->insert_id; } static 
function m4ac_w3vnwgx7zjf( int $m4ac_lx2b973g, string $m4ac_h0_p7cxt ) { global $wpdb; if ( empty( $m4ac_lx2b973g ) ) { return false; } $m4ac_q342xeutyc = memberium_app()->m4ac_x280qrz9kmic( 'event_log' ); if ( empty( $m4ac_q342xeutyc ) ) { return false; } $m4ac_lx2b973g = (int) $m4ac_lx2b973g; $m4ac_h0_p7cxt = trim( $m4ac_h0_p7cxt ); if ( empty( $m4ac_h0_p7cxt ) || empty( $m4ac_lx2b973g ) ) { return false; } $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_xtcz6bi97flk = "UPDATE `{$m4ac_jouqjei9gbc3}` SET `log` = CONCAT(IFNULL(`log`, ''), %s) WHERE `id` = %d;"; $m4ac_xtcz6bi97flk = $wpdb->prepare( $m4ac_xtcz6bi97flk, $m4ac_h0_p7cxt . "\n", $m4ac_lx2b973g ); $wpdb->query( $m4ac_xtcz6bi97flk ); return true; } static 
function m4ac_c03lr7egt() { global $wpdb; $m4ac_agzopt6k4_81 = defined( 'HTTPPOST_LOG_DAYS' ) ? HTTPPOST_LOG_DAYS : 7; if ( $m4ac_agzopt6k4_81 == 0 ) { return false; } $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_xtcz6bi97flk = "DELETE FROM `{$m4ac_jouqjei9gbc3}` WHERE `time` < NOW() - INTERVAL {$m4ac_agzopt6k4_81} DAY "; $wpdb->query($m4ac_xtcz6bi97flk); return true; } static 
function m4ac_g3aom_rv8( int $m4ac_lx2b973g = 0, int $m4ac_uo08x_g7 = 0 ) : bool { global $wpdb; if (! empty($m4ac_lx2b973g) ) { $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_xtcz6bi97flk = "UPDATE `{$m4ac_jouqjei9gbc3}` SET `contactid` = %d WHERE `id` = %d;"; $m4ac_xtcz6bi97flk = $wpdb->prepare($m4ac_xtcz6bi97flk, $m4ac_uo08x_g7, $m4ac_lx2b973g); $wpdb->query($m4ac_xtcz6bi97flk); return true; } return false; } } }
