<?php
/**
 * Copyright (c) 2018-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_tl5skz6cfptr { const LICENSE_SERVER_URL = 'https://licenseserver.webpowerandlight.com/getlicense.php'; const DEV_LICENSE_SERVER_URL = 'https://licenseserver.webpowerandlight.com/getlicense-dev.php'; private static 
function m4ac_fus1e5x0() { static $m4ac_fbfqrjzc = ''; if (empty($m4ac_fbfqrjzc)) { $m4ac_fbfqrjzc = preg_replace('/^www\./', '', strtolower(parse_url(get_bloginfo('url'), PHP_URL_HOST) ) ); } return $m4ac_fbfqrjzc; } private static 
function m4ac__5u9ndbhyx0t() { $m4ac_ccn07vmlhdg = function_exists('wp_get_environment_type') ? wp_get_environment_type() : 'production';  $m4ac_upwqy_51nxj = [ 'local' => self::LICENSE_SERVER_URL, 'development' => self::LICENSE_SERVER_URL, 'staging' => self::LICENSE_SERVER_URL, 'production' => self::LICENSE_SERVER_URL, ]; $m4ac_atr94xdeg3 = isset($m4ac_upwqy_51nxj[$m4ac_ccn07vmlhdg]) ? $m4ac_upwqy_51nxj[$m4ac_ccn07vmlhdg] : LICENSE_SERVER_URL; $m4ac_cwimbugn = memberium_app()->m4ac_lx4jv6fi7k(); $m4ac_e0z43gx7e = get_bloginfo('admin_email'); $m4ac_us5k0l_jb = m4ac_tl5skz6cfptr::m4ac_gd1pbm4e(); $m4ac_o3kw2_4u1y = phpversion(); $m4ac_xqrupw5i = parse_url(get_bloginfo('url'), PHP_URL_HOST); $m4ac_n145ehr20k6_ = memberium_app()->m4ac_cbc5pz_ng4(); $m4ac_yvyosepl6 = [ 'admin' => rawurlencode($m4ac_e0z43gx7e), 'domain' => rawurlencode($m4ac_xqrupw5i), 'env' => rawurlencode($m4ac_ccn07vmlhdg), 'm4ac' => rawurlencode($m4ac_cwimbugn), 'php' => rawurlencode($m4ac_o3kw2_4u1y), 'users' => rawurlencode($m4ac_us5k0l_jb), 'wp' => rawurlencode($m4ac_n145ehr20k6_), ]; $m4ac_atr94xdeg3 = add_query_arg($m4ac_yvyosepl6, $m4ac_atr94xdeg3); return $m4ac_atr94xdeg3; } private static 
function m4ac_l96kopfx7ty() { $m4ac_s2abgdqi4w0_ = get_option('active_plugins', []); $m4ac_s2abgdqi4w0_ = array_filter($m4ac_s2abgdqi4w0_, function($m4ac_ihnr7cyv) { return stripos($m4ac_ihnr7cyv, 'memberium-ac.php') === false; }, 0); update_option('active_plugins', $m4ac_s2abgdqi4w0_); if (! headers_sent() ) { if (is_admin() ) { wp_redirect(admin_url(), 302, 'Memberium ' . __FUNCTION__ . '::' . __LINE__); } else { wp_redirect(get_home_url(), 302, 'Memberium ' . __FUNCTION__ . '::' . __LINE__); } exit; } }    static 
function m4ac_p1ek48mj() { $m4ac_z_6opwls0e7 = m4ac_tl5skz6cfptr::m4ac_a9x5p_oeaqu1();  return (boolean) $m4ac_z_6opwls0e7['trial_mode']; }  static 
function m4ac_qea6zr047() { global $wpdb; $m4ac_us5k0l_jb = $wpdb->get_var("SELECT COUNT(*) FROM `{$wpdb->users}`"); update_option('wpal/census', base_convert($m4ac_us5k0l_jb, 10, 36), true); return $m4ac_us5k0l_jb; }  static 
function m4ac_gd1pbm4e() { $m4ac_us5k0l_jb = base_convert(get_option('wpal/census', 0), 36, 10); if (! $m4ac_us5k0l_jb ) { $m4ac_us5k0l_jb = self::m4ac_qea6zr047(); } return $m4ac_us5k0l_jb; }   static 
function m4ac_e28auldn() { static $m4ac_c4xyarg91 = -1; if ($m4ac_c4xyarg91 !== -1) { return (bool) $m4ac_c4xyarg91;  } $m4ac_z_6opwls0e7 = self::m4ac_a9x5p_oeaqu1(); if (! isset($m4ac_z_6opwls0e7['active']) || ! $m4ac_z_6opwls0e7['active']) { $m4ac_w386fgqma2 = self::m4ac_f1w9jlh37i(); $m4ac_z_6opwls0e7 = m4ac_tl5skz6cfptr::m4ac_a9x5p_oeaqu1($m4ac_w386fgqma2); }  $m4ac_c4xyarg91 = isset($m4ac_z_6opwls0e7['active']) ? (bool) $m4ac_z_6opwls0e7['active'] : false; return $m4ac_c4xyarg91; } static 
function m4ac_a9x5p_oeaqu1($m4ac_s3onxijv = '') { $m4ac_yqzoa68v = [ 'active' => 0, 'kill' => 0, 'next_check' => time() + 900, 'now' => time(), 'renewal_date' => time() + 900, 'trial_mode' => 0, 'valid' => 0, ]; if (empty($m4ac_s3onxijv)) { $m4ac_s3onxijv = get_option('memberium_license', ''); } if (empty($m4ac_s3onxijv)) { return $m4ac_yqzoa68v; } $m4ac_bac0ixmlwf = 3; $m4ac_v6kd29m1sn = 32; $m4ac_fic2e07vfkz['valid'] = 0; $m4ac_fic2e07vfkz['kill'] = 0; $m4ac_fic2e07vfkz['trial_mode'] = 0; $m4ac_jgniouf_v = self::m4ac_fus1e5x0(); $m4ac_hin9xd7p = memberium_app()->m4ac_x280qrz9kmic('random_seed'); $m4ac_yx5m1hnpjuq = strtolower(trim($m4ac_hin9xd7p . $m4ac_jgniouf_v) ); if ($m4ac_bac0ixmlwf == 3) { $m4ac_hbyinlm5vw = substr($m4ac_s3onxijv, 0, 32); $m4ac_xa0v7dbn3ker = unserialize(base64_decode(substr($m4ac_s3onxijv, 32) ) ); $m4ac_fm2607pvb8o = md5(serialize($m4ac_xa0v7dbn3ker) . strtolower($m4ac_hin9xd7p) . strtolower($m4ac_jgniouf_v) );  if ($m4ac_fm2607pvb8o == $m4ac_hbyinlm5vw) { $m4ac_fic2e07vfkz = $m4ac_xa0v7dbn3ker; $m4ac_fic2e07vfkz['valid'] = 1; } else { $m4ac_fic2e07vfkz['valid'] = 0; } if ($m4ac_fic2e07vfkz['valid']) { $m4ac_fic2e07vfkz['now'] = time(); $m4ac_fic2e07vfkz['check_ttl'] = $m4ac_fic2e07vfkz['next_check'] - time(); $m4ac_fic2e07vfkz['expiration_ttl'] = $m4ac_fic2e07vfkz['renewal_date'] - time(); $m4ac_fic2e07vfkz['active'] = isset($m4ac_xa0v7dbn3ker['active']) ? $m4ac_xa0v7dbn3ker['active'] : 0; $m4ac_fic2e07vfkz['kill'] = isset($m4ac_xa0v7dbn3ker['kill']) ? $m4ac_xa0v7dbn3ker['kill'] : 0; $m4ac_fic2e07vfkz['max_users'] = isset($m4ac_xa0v7dbn3ker['max_users']) ? $m4ac_xa0v7dbn3ker['max_users'] : 50; $m4ac_fic2e07vfkz['max_version'] = isset($m4ac_xa0v7dbn3ker['max_version']) ? $m4ac_xa0v7dbn3ker['max_version'] : 0; $m4ac_fic2e07vfkz['min_version'] = isset($m4ac_xa0v7dbn3ker['min_version']) ? $m4ac_xa0v7dbn3ker['min_version'] : 0; $m4ac_fic2e07vfkz['next_check'] = isset($m4ac_xa0v7dbn3ker['next_check']) ? $m4ac_xa0v7dbn3ker['next_check'] : 0; $m4ac_fic2e07vfkz['renewal_date'] = isset($m4ac_xa0v7dbn3ker['renewal_date']) ? $m4ac_xa0v7dbn3ker['renewal_date'] : 0; $m4ac_fic2e07vfkz['trial_mode'] = isset($m4ac_xa0v7dbn3ker['trial_mode']) ? $m4ac_xa0v7dbn3ker['trial_mode'] : 0; $m4ac_fic2e07vfkz['version'] = isset($m4ac_xa0v7dbn3ker['version']) ? $m4ac_xa0v7dbn3ker['version'] : 0; $m4ac_fic2e07vfkz['owner_email'] = isset($m4ac_xa0v7dbn3ker['owner_email']) ? $m4ac_xa0v7dbn3ker['owner_email'] : ''; $m4ac_fic2e07vfkz['license_name'] = isset($m4ac_xa0v7dbn3ker['license_name']) ? $m4ac_xa0v7dbn3ker['license_name'] : ''; if (! empty($m4ac_fic2e07vfkz['kill']) ) { self::m4ac_l96kopfx7ty(); } } } if ($m4ac_fic2e07vfkz['valid']) { if ($m4ac_fic2e07vfkz['expiration_ttl'] < 1) { $m4ac_fic2e07vfkz['valid'] = 0; } } if ($m4ac_fic2e07vfkz['valid']) { if (self::m4ac_gd1pbm4e() > $m4ac_fic2e07vfkz['max_users']) { $m4ac_fic2e07vfkz['active'] = 0; } } return $m4ac_fic2e07vfkz; }   static 
function m4ac_f1w9jlh37i($m4ac_q3_aoy0q1d8 = false) { if (! memberium_app()->m4ac_x280qrz9kmic('ac_api_verified') ) { return; } if ($m4ac_q3_aoy0q1d8 === false) { if (function_exists('is_admin') && (! is_admin() ) ) { $m4ac_sjdomslph6 = (time() - get_option('memberium/licenseserver/updated', 0) ); if ($m4ac_sjdomslph6 < 28800) { return get_option('memberium_license'); } } } update_option('memberium/licenseserver/updated', time(), true); $m4ac_xvjwbts4g = self::m4ac__5u9ndbhyx0t(); $m4ac_w386fgqma2 = ''; $m4ac_jkcodjzp = memberium_app()->m4ac_yiqu4k3xj5()->api('account/view');  $m4ac_h57xqitcp = is_object($m4ac_jkcodjzp) ? trim($m4ac_jkcodjzp->account) : ''; $m4ac_n50u3alz1 = is_object($m4ac_jkcodjzp) ? $m4ac_jkcodjzp->subscriber_limit : 0; $m4ac_m26yhm_7 = is_object($m4ac_jkcodjzp) ? $m4ac_jkcodjzp->status : 0; $m4ac_wqc45t1ifw = is_object($m4ac_jkcodjzp) ? $m4ac_jkcodjzp->email : ''; $m4ac_qske8viao = empty($m4ac_jkcodjzp->trial) ? 0 : $m4ac_jkcodjzp->trial; $m4ac_x3vgd9ci = is_object($m4ac_jkcodjzp) ? $m4ac_jkcodjzp->fname : ''; $m4ac_zni6508th = is_object($m4ac_jkcodjzp) ? $m4ac_jkcodjzp->lname : ''; $m4ac_ccn07vmlhdg = function_exists('wp_get_environment_type') ? wp_get_environment_type() : 'production'; if (empty($m4ac_h57xqitcp) ) { $m4ac_hm_o67zdsr = memberium_app()->m4ac_x280qrz9kmic('ac_api_url'); $m4ac_h57xqitcp = substr($m4ac_hm_o67zdsr, strpos($m4ac_hm_o67zdsr, '//') + 2, strpos($m4ac_hm_o67zdsr, '.') ); $m4ac_h57xqitcp = substr($m4ac_h57xqitcp, 0, strpos($m4ac_h57xqitcp, '.') ) . '.activehosted.com'; } $m4ac_x410ukrvbs7 = [ 'hostname' => self::m4ac_fus1e5x0(), 'environment' => $m4ac_ccn07vmlhdg, 'admin_email' => get_bloginfo('admin_email'), 'url' => get_bloginfo('url'), 'license_key' => '', 'user_count' => self::m4ac_gd1pbm4e(), 'version' => memberium_app()->m4ac_lx4jv6fi7k(), 'sku' => 'M4AC', 'ip_address' => $_SERVER['SERVER_ADDR'], 'php_version' => phpversion(), 'ioncube_version' => 'none', 'checksum' => memberium_app()->m4ac_x280qrz9kmic('random_seed'), 'appname' => $m4ac_h57xqitcp, 'ac_subscriber_limit' => $m4ac_n50u3alz1, 'ac_status' => $m4ac_m26yhm_7, 'ac_trial' => $m4ac_qske8viao, 'ac_admin_email' => $m4ac_wqc45t1ifw, 'ac_admin_firstname' => $m4ac_x3vgd9ci, 'ac_admin_lastname' => $m4ac_zni6508th, 'interval' => 32, 'protocol_version' => 3, ]; $m4ac_ah90o86m = [ 'method' => 'POST', 'timeout' => 10, 'redirection' => 5, 'httpversion' => '1.0', 'blocking' => true, 'headers' => [], 'body' => $m4ac_x410ukrvbs7, 'cookies' => [], ]; $m4ac_fmp1cur9 = wp_remote_post($m4ac_xvjwbts4g, $m4ac_ah90o86m); if (is_array($m4ac_fmp1cur9) ) { $m4ac_w386fgqma2 = $m4ac_fmp1cur9['body']; $m4ac_z_6opwls0e7 = self::m4ac_a9x5p_oeaqu1($m4ac_w386fgqma2); if ($m4ac_z_6opwls0e7['valid'] == 1) { update_option('memberium_license', $m4ac_w386fgqma2); } else { $m4ac_w386fgqma2 = get_option('memberium_license'); } } return $m4ac_w386fgqma2; }   static 
function m4ac_s8n7dqso_() { static $m4ac_jyiw4bsu1jv = false; if ($m4ac_jyiw4bsu1jv === false) { $m4ac_w386fgqma2 = self::m4ac_a9x5p_oeaqu1(); $m4ac_jyiw4bsu1jv = isset($m4ac_w386fgqma2['tags']) ? $m4ac_w386fgqma2['tags'] : ''; $m4ac_jyiw4bsu1jv = explode(',', strtolower($m4ac_jyiw4bsu1jv) ); } return $m4ac_jyiw4bsu1jv; }   static 
function m4ac_efe5yorv($m4ac_q5l6gsx70) {  if (! is_array($m4ac_q5l6gsx70) ) { $m4ac_q5l6gsx70 = explode(',', $m4ac_q5l6gsx70); } if (is_array($m4ac_q5l6gsx70) ) {  $m4ac_jyiw4bsu1jv = self::m4ac_s8n7dqso_(); foreach($m4ac_q5l6gsx70 as $m4ac_o75qrnlisk) { if (in_array($m4ac_o75qrnlisk, $m4ac_jyiw4bsu1jv) ) { return true; } } } return false; } } }
