<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) {  final 
class m4ac_kz0av3byx { 
function __construct() { if ($_SERVER['REQUEST_METHOD'] == 'POST') { if (! empty($_GET['key']) ) { if ($this->m4ac_t9cawqso0ntk($_GET['key']) ) { $m4ac_ah90o86m = [ 'type' => 'webhook', 'contact_id' => isset($_POST['contact']['id']) ? $_POST['contact']['id'] : 0, ]; $this->log_id = m4ac_eghsod68x::m4ac_hozfsg3t($m4ac_ah90o86m, "ActiveCampaign Webhook Initiated"); $this->webhook_start_time = microtime(); add_action('wp_loaded', [$this, 'm4ac_o8i_feh6jqx1'], 1000); add_action('m4ac/webhook/math', [$this, 'm4ac_i35yhecwix'], 10, 1); } else { $m4ac_ah90o86m = [ 'type' => 'webhook', ]; $this->log_id = m4ac_eghsod68x::m4ac_hozfsg3t($m4ac_ah90o86m, 'Invalid Webhook Key ' . $_SERVER['REQUEST_URI']) ; return; } }   if (! empty($_POST['thrivecart_secret']) ) { if ($_POST['thrivecart_secret'] == memberium_app()->m4ac_x280qrz9kmic('thrivecart_secret') ) { $this->m4ac_eqab9gfv4ey2(); } } } } 
function m4ac_o8i_feh6jqx1() { memberium_app()->m4ac_uvx0d_oj8(true); header('HTTP/1.1 200 OK'); $m4ac_cc39jsy5 = false; $m4ac_qsvd0m6oq = $this->m4ac_cfuek9sqwda($_POST); $m4ac_ymh_q5ubyn = isset($_GET['job']) ? strtolower(trim($_GET['job']) ) : 'Update'; $m4ac_uo08x_g7 = isset($m4ac_qsvd0m6oq['data']['id']) ? (int) $m4ac_qsvd0m6oq['data']['id'] : 0; $m4ac_d78sk4qc3i = isset($m4ac_qsvd0m6oq['standard']['email']) ? $m4ac_qsvd0m6oq['standard']['email'] : ''; $m4ac_at_5xofh = memberium_app()->m4ac_ncpeg876f5sl($m4ac_uo08x_g7, $m4ac_d78sk4qc3i); m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, 'Action: ' . ucwords(strtr($m4ac_ymh_q5ubyn, '_', ' ') )); m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, 'Email: ' . $m4ac_qsvd0m6oq['standard']['email']); m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "Contact ID: {$m4ac_uo08x_g7}, User ID: {$m4ac_at_5xofh}"); if (empty($m4ac_qsvd0m6oq['standard']['email']) ) { m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, 'Error: Email Address Empty.  No action taken.'); $m4ac_cc39jsy5 = true; } if (empty($m4ac_qsvd0m6oq['standard']['first_name']) ) { m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, 'Error: First Name Empty.  No action taken.'); $m4ac_cc39jsy5 = true; } if (! $m4ac_cc39jsy5) { if ($m4ac_ymh_q5ubyn == 'deleteuser') { $this->m4ac_o35b_48j($m4ac_qsvd0m6oq); } else { if ($m4ac_ymh_q5ubyn == 'createuser') { memberium_app()->m4ac_aqjm2ebo($m4ac_qsvd0m6oq); $m4ac_lzqa4dthg = isset($_GET['overwrite']) ? (bool) strtolower(trim($_GET['overwrite']) ) : false; if ($m4ac_lzqa4dthg || $m4ac_at_5xofh == 0) { $m4ac_bxvpge5qkdo9 = []; $m4ac_bxvpge5qkdo9['overwrite'] = $m4ac_lzqa4dthg; $this->m4ac_sujc_t69r($m4ac_qsvd0m6oq, $m4ac_bxvpge5qkdo9); $m4ac_sre8f51b = true; m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "User Created"); } } elseif ($m4ac_ymh_q5ubyn > '') { if ($m4ac_uo08x_g7 && $m4ac_at_5xofh) { memberium_app()->m4ac_aqjm2ebo($m4ac_qsvd0m6oq); memberium_app()->m4ac_e538xo4yks($m4ac_uo08x_g7); } $m4ac_ah90o86m = [ 'contact_id' => $m4ac_uo08x_g7, 'contact' => $m4ac_qsvd0m6oq, 'get' => $_GET, 'log_id' => $this->log_id, 'post' => $_POST, 'user_id' => $m4ac_at_5xofh, ]; do_action("m4ac/webhook/{$m4ac_ymh_q5ubyn}", $m4ac_ah90o86m); } $m4ac__crsbi5yuze = memberium_app()->m4ac_c17vlcx3a4($m4ac_at_5xofh); } memberium_app()->m4ac_uvx0d_oj8(false); } $this->webhook_end_time = microtime(); $m4ac_n5cxe760 = abs($this->webhook_end_time - $this->webhook_start_time); m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "Webhook Completed in {$m4ac_n5cxe760}secs"); if (WP_DEBUG || MEMBERIUM_DEBUG) { m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "POST:  " . serialize($_POST) ); } } private 
function m4ac_cfuek9sqwda(array $m4ac_maz5nvkp) { $m4ac_qsvd0m6oq = []; if (is_array($m4ac_maz5nvkp['contact']) && ! empty($m4ac_maz5nvkp['contact']) ) { $m4ac_qsvd0m6oq['data']['id'] = isset($m4ac_maz5nvkp['contact']['id']) ? $m4ac_maz5nvkp['contact']['id'] : 0; $m4ac_qsvd0m6oq['standard']['email'] = isset($m4ac_maz5nvkp['contact']['email']) ? trim(strtolower($m4ac_maz5nvkp['contact']['email']) ) : ''; $m4ac_qsvd0m6oq['standard']['first_name'] = isset($m4ac_maz5nvkp['contact']['first_name']) ? $m4ac_maz5nvkp['contact']['first_name'] : ''; $m4ac_qsvd0m6oq['standard']['ip'] = isset($m4ac_maz5nvkp['contact']['ip']) ? $m4ac_maz5nvkp['contact']['ip'] : ''; $m4ac_qsvd0m6oq['standard']['last_name'] = isset($m4ac_maz5nvkp['contact']['last_name']) ? $m4ac_maz5nvkp['contact']['last_name'] : ''; $m4ac_qsvd0m6oq['standard']['orgname'] = isset($m4ac_maz5nvkp['contact']['orgname']) ? $m4ac_maz5nvkp['contact']['orgname'] : ''; $m4ac_qsvd0m6oq['standard']['phone'] = isset($m4ac_maz5nvkp['contact']['phone']) ? $m4ac_maz5nvkp['contact']['phone'] : ''; $m4ac_qsvd0m6oq['standard']['tags'] = isset($m4ac_maz5nvkp['contact']['tags']) ? trim(str_replace(', ', ',', $m4ac_maz5nvkp['contact']['tags']) ) : ''; $m4ac_qsvd0m6oq['custom'] = isset($m4ac_maz5nvkp['contact']['fields']) ? $m4ac_maz5nvkp['contact']['fields'] : []; } return $m4ac_qsvd0m6oq; } 
function m4ac_uei4qzktsa() { $m4ac_lqg2ejwks8 = get_option(MEMBERIUM_CORE_SETTINGS, [] ); $m4ac_ah4c_sou = explode(',', $m4ac_lqg2ejwks8['http_post_key']); $m4ac_dkuqmoh18w = array_shift($m4ac_ah4c_sou); $m4ac_kx_kwy1ig = (array) (get_site_url() . '/?type=contact&key=' . $_POST['auth_key']); return $m4ac_kx_kwy1ig; } 
function m4ac_vgtyda_kox() { $m4ac_qq68icplb9 = memberium_app()->m4ac_yiqu4k3xj5(); $m4ac_y678mgix = $m4ac_qq68icplb9->api('webhook/list'); $m4ac_tf18usj90b7 = $this->m4ac_uei4qzktsa(); $m4ac_wvut_p4gok57 = 'Memberium AC for ' . get_site_url(); $m4ac_tp09y21w7hcn = false; foreach($m4ac_y678mgix as $m4ac_r8b1zst2) { if (is_object($m4ac_r8b1zst2) ) { if ($m4ac_wvut_p4gok57 == $m4ac_r8b1zst2->name && in_array($m4ac_r8b1zst2->url, $m4ac_tf18usj90b7) ) { $m4ac_tp09y21w7hcn = true; } } } if (! $m4ac_tp09y21w7hcn) { $m4ac_r7yve3xqc5tm = isset($_POST['list_id']) ? $_POST['list_id'] : 0; $m4ac_bxvpge5qkdo9 = [ 'name' => $m4ac_wvut_p4gok57, 'url' => $m4ac_tf18usj90b7[0], 'lists[0]' => $m4ac_r7yve3xqc5tm, 'action[0]' => 'update', 'init[0]' => 'public', 'init[1]' => 'system', 'init[2]' => 'admin', 'init[3]' => 'api',        ]; $m4ac_fic2e07vfkz = $m4ac_qq68icplb9->api('webhook/add', $m4ac_bxvpge5qkdo9); } return $m4ac_tp09y21w7hcn; } 
function m4ac_ojds78kz() { $m4ac_tokbjqv5 = $this->m4ac_vgtyda_kox(); if (! $m4ac_tokbjqv5) {  } else {  } echo '<br>'; } private 
function m4ac_t9cawqso0ntk(string $m4ac_ukqvxo6ne7) { $m4ac_rsgp378wz = array_filter( explode(',', memberium_app()->m4ac_x280qrz9kmic('http_post_key') ) ); if (empty($m4ac_ukqvxo6ne7) || ! in_array($m4ac_ukqvxo6ne7, $m4ac_rsgp378wz) ) { return false; } else { return true; } } 
function m4ac_eqab9gfv4ey2() {  if (WP_DEBUG || MEMBERIUM_DEBUG) { m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "POST:  " . serialize($_POST) ); } else { m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, serialize($_POST) ); } }    
function m4ac_sujc_t69r(array $m4ac_qsvd0m6oq, array $m4ac_bxvpge5qkdo9) { global $wpdb; m4ac_eghsod68x::m4ac_w3vnwgx7zjf($this->log_id, "Overwrite = " . $m4ac_bxvpge5qkdo9['overwrite']); $m4ac_lzqa4dthg = isset($m4ac_bxvpge5qkdo9['overwrite']) ? (bool) $m4ac_bxvpge5qkdo9['overwrite'] : false; $m4ac_ya4km5wlsd = isset($m4ac_bxvpge5qkdo9['debug']) ? (bool) $m4ac_bxvpge5qkdo9['debug'] : false; $m4ac_hpti3o8l = isset($m4ac_bxvpge5qkdo9['add_automation']) ? (int) $m4ac_bxvpge5qkdo9['add_automation'] : 0; $m4ac_kasx75yqvrc = isset($m4ac_bxvpge5qkdo9['update_automation']) ? (int) $m4ac_bxvpge5qkdo9['update_automation'] : 0; $m4ac_uo08x_g7 = isset($m4ac_qsvd0m6oq['data']['id']) ? (int) $m4ac_qsvd0m6oq['data']['id'] : 0; if (empty($m4ac_uo08x_g7) ) { return; } $m4ac_umuw7621 = false; $m4ac_ura2ktgl = false; $m4ac_uo08x_g7 = $m4ac_uo08x_g7; $m4ac_bxvpge5qkdo9 = [ 'overwrite' => $m4ac_lzqa4dthg, 'add_automation' => $m4ac_hpti3o8l, 'update_automation' => $m4ac_kasx75yqvrc, ]; memberium_app()->m4ac_e538xo4yks($m4ac_uo08x_g7, $m4ac_bxvpge5qkdo9); } 
function m4ac_o35b_48j(array $m4ac_qsvd0m6oq) {  $m4ac_uo08x_g7 = isset($m4ac_qsvd0m6oq['data']['id']) ? (int) $m4ac_qsvd0m6oq['data']['id'] : 0; if ($m4ac_uo08x_g7 > 0) { $m4ac_at_5xofh = m4ac_bem2ya5k::m4ac_y4vi6m8f1qhj($m4ac_uo08x_g7); if ($m4ac_at_5xofh > 0) { if (! user_can($m4ac_at_5xofh, 'manage_options') ) { include_once ABSPATH . '/wp-admin/includes/user.php'; if (function_exists('wp_delete_user')) { wp_delete_user($m4ac_at_5xofh, false); return true; } else { } } } else { } } return false; } 
function m4ac_i35yhecwix(array $m4ac_ah90o86m) { } 
function m4ac_vlej9ft6pbq(array $m4ac_ah90o86m) { } static 
function m4ac_zw_dhmca() : self { return self::$m4ac_u4tpxcro19 ? self::$m4ac_u4tpxcro19 : self::$m4ac_u4tpxcro19 = new self; } static private $m4ac_u4tpxcro19; private $log_id = 0; private $webhook_start_time = 0; private $webhook_end_time = 0; } }
