<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_nukiz24xg { 
function m4ac_joch_re68k(array $m4ac_qz2fsdy3pb) { $m4ac_uoxln5w4m = [ 'achievement-type', 'attachment', 'badges', 'gamipress_logs', 'gamipress_user_earnings', 'points-type', 'rank-type', ]; $m4ac_kpc4wrkgnqiy = $this->m4ac_sgd5bsznq(); return array_merge($m4ac_qz2fsdy3pb, $m4ac_kpc4wrkgnqiy, $m4ac_uoxln5w4m); } 
function m4ac_sgd5bsznq() { $m4ac_uvbwy6m8tqzj = gamipress_get_achievement_types_slugs(); $m4ac_rktjxq_v = gamipress_get_rank_types_slugs(); $m4ac_mrvf86iwd5 = gamipress_get_points_types_slugs(); return array_merge($m4ac_uvbwy6m8tqzj, $m4ac_rktjxq_v); } 
function m4ac_pljf5peh() { global $post; $m4ac_jd036_b2s = get_post_meta($post->ID, '_memberium_tag', true); $m4ac_cyo9_48uxk = get_post_meta($post->ID, '_memberium_automation', true); $m4ac_x16i5xouf = get_post_meta($post->ID, '_memberium_badge_add', true); $m4ac_qr2kxcmulte = m4ac_ppbzvcq5k0ie::m4ac_zw_dhmca()->m4ac_vo9h4csm($post->ID); $m4ac_sv5rmko0 = ucwords($m4ac_qr2kxcmulte); wp_nonce_field(__CLASS__, "memberium/gamipress/metabox/achievement/{$post->ID}"); echo '<style> .memberium-badgeos-achievement-metabox-input {width:100%; max-width:100%}</style>'; echo '<p>When this is rewarded to a user...</p>'; echo '<label for="_memberium_tag">', _e("Apply Tag", 'memberium'), ':</label> '; echo '<input name="_memberium_tag" class="taglistdropdown memberium-badgeos-achievement-metabox-input" value="', (empty($m4ac_jd036_b2s) ? 0 : $m4ac_jd036_b2s), '"><br /><br />'; echo '<label for="_memberium_automation">', _e("Run Automation", 'memberium'), ':</label> '; echo '<input name="_memberium_automation" class="automationdropdown memberium-badgeos-achievement-metabox-input" value="', (empty($m4ac_cyo9_48uxk) ? 0 : $m4ac_cyo9_48uxk), '"><br /><br />'; if (in_array($m4ac_qr2kxcmulte, ['achievement', 'rank']) ) { echo '<label for="_memberium_badge_add">', _e("Achieve if Member has Tag", 'memberium'), ':</label> '; echo '<input name="_memberium_badge_add" class="taglistdropdown memberium-badgeos-achievement-metabox-input" value="', (empty($m4ac_x16i5xouf) ? 0 : $m4ac_x16i5xouf), '"><br /><br />'; } memberium_app()->m4ac_dfujoe3avi_()->m4ac_iy1htpsfj(); } 
function m4ac_b0qd9cuhwf(int $m4ac__37l6rhivt2 = 0) { if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) { return; } if (! current_user_can('edit_posts', $m4ac__37l6rhivt2) ) { return; } if (empty($_POST["memberium/gamipress/metabox/achievement/{$m4ac__37l6rhivt2}"]) || ! wp_verify_nonce($_POST["memberium/gamipress/metabox/achievement/{$m4ac__37l6rhivt2}"], __CLASS__) ) { return; } $m4ac_ah4c_sou = [ '_memberium_tag', '_memberium_automation', '_memberium_badge_add', ]; foreach($m4ac_ah4c_sou as $m4ac_egl6dkai) { if (isset($_POST[$m4ac_egl6dkai]) ) { $elf_result = empty($_POST[$m4ac_egl6dkai]) ? delete_post_meta($m4ac__37l6rhivt2, $m4ac_egl6dkai) : update_post_meta($m4ac__37l6rhivt2, $m4ac_egl6dkai, $_POST[$m4ac_egl6dkai]); } } $this->m4ac_dyqukh75g(); } 
function m4ac_ip5kb3v4cqm() { $m4ac_dxtjcmeridh = m4ac_s126v0fexga::m4ac_udme4nbtp(); $m4ac_xld0g1xi9s = $this->m4ac_sgd5bsznq(); $m4ac_rycr7jk3ta = in_array($m4ac_dxtjcmeridh, $m4ac_xld0g1xi9s); if ($m4ac_dxtjcmeridh == 'points-type') { if ('71.92.64.210' == $_SERVER['REMOTE_ADDR']) { add_meta_box('gamipress-points-features', 'Memberium GamiPress Points', [$this, 'm4ac_ak_fohnu6clj'], $m4ac_dxtjcmeridh, 'side'); } } elseif ($m4ac_rycr7jk3ta) { add_meta_box('gamipress-achievement-features', 'Memberium GamiPress Integration', [$this, 'm4ac_pljf5peh'], $m4ac_dxtjcmeridh, 'side'); } add_action('save_post', [$this, 'm4ac_b0qd9cuhwf']); add_action('save_post', [$this, 'm4ac_jbuz_g06he']); } private 
function m4ac_dyqukh75g() { $m4ac_ah90o86m = [ 'numberposts' => -1, 'order' => 'ASC', 'orderby' => 'ID', 'post_status' => 'publish', 'post_type' => gamipress_get_achievement_types_slugs(), 'fields' => 'ids', ]; $m4ac_lel0isn7jtkw = get_posts($m4ac_ah90o86m); $m4ac_ckfu62mpdy = []; foreach($m4ac_lel0isn7jtkw as $m4ac_lj_fwoc5ub1y) { $m4ac_o75qrnlisk = get_post_meta($m4ac_lj_fwoc5ub1y, '_memberium_badge_add', true); if ($m4ac_o75qrnlisk) { $m4ac_ckfu62mpdy[$m4ac_lj_fwoc5ub1y] = $m4ac_o75qrnlisk; } } update_option('memberium/gamipress/assign_by_tag', $m4ac_ckfu62mpdy); } private 
function m4ac_rh6ijntd() { add_action('admin_init', [$this, 'm4ac_ip5kb3v4cqm']); add_filter('memberium/unenhanced_posts', [$this, 'm4ac_joch_re68k'], 10, 1); } private 
function __construct() { $this->m4ac_rh6ijntd(); } static 
function m4ac_zw_dhmca() : self { static $m4ac_u4tpxcro19 = false; return $m4ac_u4tpxcro19 ? $m4ac_u4tpxcro19 : $m4ac_u4tpxcro19 = new self; }    
function m4ac_ak_fohnu6clj() { global $post; $m4ac_wc9s2dnt4y = get_post_meta($post->ID, '_memberium_field', true); wp_nonce_field(__CLASS__, "memberium/gamipress/metabox/points/{$post->ID}"); } 
function m4ac_jbuz_g06he(int $m4ac__37l6rhivt2 = 0) { }  } }
