<?php
/**
 * Copyright (c) 2020 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) {  
class m4ac_byoqkcalxi { private $scripts_loaded = false; private $fields = null; private $rendered_nonce = false;  
function m4ac_hfr7ukej(){ if( ! is_null( $this->fields ) ){ return $this->fields; } $m4ac_kbagjrq9 = WPAL_WIDGET_KEY_NAME; $m4ac_qb48jahn0kc = WPAL_WIDGET_ACCESS_LEVEL_NAME; $m4ac_v4m532o6 = " " . __( "settings are only available for logged in users." ); $this->fields = apply_filters('wpal/widget/fields', [ [ 'name' => 'status', 'label' => __('User Status'), 'type' => 'select2', 'data' => 'status', 'disable-search' => true, 'change' => 'wpal_widget_access_status_toggle', 'priority' => 100 ], [ 'name' => 'memberships', 'label' => $m4ac_qb48jahn0kc, 'info' => $m4ac_qb48jahn0kc . $m4ac_v4m532o6, 'type' => 'select2', 'data' => 'levels', 'change' => 'wpal_widget_contact_toggle', 'multiple' => 1, 'priority' => 200 ], [ 'name' => 'tags1', 'label' => $m4ac_kbagjrq9, 'info' => $m4ac_kbagjrq9 . $m4ac_v4m532o6, 'type' => 'select2', 'data' => 'keys', 'change' => 'wpal_widget_contact_toggle', 'multiple' => 1, 'priority' => 300 ], [ 'name' => 'tags2', 'label' => __("AND") . " {$m4ac_kbagjrq9}", 'info' => "The contact must have both the 1st {$m4ac_kbagjrq9} AND this {$m4ac_kbagjrq9} in order to view this item and these {$m4ac_v4m532o6}", 'type' => 'select2', 'data' => 'keys', 'change' => 'wpal_widget_contact_toggle', 'multiple' => 1, 'priority' => 400 ], [ 'name' => 'eval', 'label' => __("PHP Boolean Expression"), 'type' => 'textarea', 'desc' => __('Enter a boolean expression which evaluates to true to show or false to hide this element.'), 'priority' => 500 ], ] ); return $this->fields; }  
function m4ac_wcael1z6($m4ac_cwimbugn){ if ($this->scripts_loaded){ return; } $m4ac_atr94xdeg3 = trailingslashit(plugin_dir_url(__FILE__)) . 'assets/'; $m4ac_lkcphno6l0v1 = ['jquery']; wp_enqueue_style("wpal-widget-access-css", "{$m4ac_atr94xdeg3}widget.css", [], $m4ac_cwimbugn, "all"); wp_enqueue_script("wpal-widget-access-js", "{$m4ac_atr94xdeg3}widget.js", $m4ac_lkcphno6l0v1, $m4ac_cwimbugn, true);  $m4ac_qo20ti1h6 = "{$m4ac_atr94xdeg3}vendor/selectwoo/"; $m4ac_kkq24nui = "wpal-widget-access-selectwoo-"; $m4ac_oucjdq1x9_ = '1.0.1'; wp_enqueue_style("{$m4ac_kkq24nui}css", "{$m4ac_qo20ti1h6}selectwoo.css", [], $m4ac_oucjdq1x9_, "all"); wp_enqueue_script("{$m4ac_kkq24nui}js", "{$m4ac_qo20ti1h6}selectwoo.full.min.js", $m4ac_lkcphno6l0v1, $m4ac_oucjdq1x9_, true);  wp_localize_script("wpal-widget-access-js", "wpal_widget_data", [ 'select2Data' => [ 'levels' => $this->m4ac_oxvlnfdp(), 'keys' => $this->m4ac_gxlef7oam(), 'status' => $this->m4ac_l6s5zjkxm() ], 'I18n' => [ 'ids_removed' => WPAL_WIDGET_IDS_REMOVED_TEXT ], 'loggedInOnlyKeys' => $this->m4ac_ti4mso7bq() ]); $this->scripts_loaded = true; }  
function m4ac_oxvlnfdp(){ $m4ac_b40ft1esgpw = apply_filters('wpal/widget/access_levels', [], 'widget'); $m4ac_md7c8zsu2o = [ [ 'id' => 'any_membership', 'text' => __('Any', 'm4ac_csga4duwvbry') . ' ' . WPAL_WIDGET_ACCESS_LEVEL_NAME ] ]; if(is_array($m4ac_b40ft1esgpw) && ! empty($m4ac_b40ft1esgpw) ){ foreach ($m4ac_b40ft1esgpw as $m4ac_lj_fwoc5ub1y => $m4ac_uk4w9mfx) { $m4ac_pzocy3nw = stripslashes($m4ac_uk4w9mfx['name']); $m4ac_uk4w9mfx = $m4ac_uk4w9mfx['level']; $m4ac_md7c8zsu2o[] = [ 'id' => (int) $m4ac_lj_fwoc5ub1y, 'text' => "{$m4ac_pzocy3nw} ({$m4ac_uk4w9mfx})" ]; } } return $m4ac_md7c8zsu2o; }  
function m4ac_gxlef7oam(){ $m4ac_md7c8zsu2o = []; $m4ac_ah4c_sou = apply_filters('wpal/widget/get_key_map', [], 'widget'); if( is_array($m4ac_ah4c_sou) && ! empty($m4ac_ah4c_sou) ){ foreach ($m4ac_ah4c_sou as $m4ac_lj_fwoc5ub1y => $m4ac_h0_p7cxt) { $m4ac_md7c8zsu2o[] = [ 'id' => $m4ac_lj_fwoc5ub1y, 'text' => $m4ac_h0_p7cxt ]; } } return $m4ac_md7c8zsu2o; } 
function m4ac_l6s5zjkxm(){ return apply_filters('wpal/widget/access/user/status', [ [ 'id' => '', 'text' => __( 'All Visitors', 'm4ac_csga4duwvbry' ) ], [ 'id' => '1', 'text' => __( 'Logged In Users Only', 'm4ac_csga4duwvbry' ) ], [ 'id' => '2', 'text' => __( 'Logged Out Visitors Only', 'm4ac_csga4duwvbry' ) ] ] ); } 
function m4ac_ti4mso7bq(){ return apply_filters('wpal/widget/logged_in_only/fields', ['memberships', 'tags1', 'tags2'] ); }  
function m4ac_b5h_0vdi4($m4ac_u4tpxcro19, $m4ac_flq1rv8wf0t) { $m4ac_u9uhl_ci87 = $this->m4ac_hfr7ukej(); if( is_array($m4ac_u9uhl_ci87) && ! empty($m4ac_u9uhl_ci87) ){ $m4ac_x_1654tdgb = 0;  foreach ($m4ac_u9uhl_ci87 as $m4ac_wc9s2dnt4y) { $m4ac_pzocy3nw = $m4ac_wc9s2dnt4y['name']; $m4ac_ihnr7cyv = ''; if( isset($m4ac_flq1rv8wf0t[$m4ac_pzocy3nw]) ){ $m4ac_ss6bwxopg8 = $m4ac_wc9s2dnt4y['type']; $m4ac_ihnr7cyv = $m4ac_flq1rv8wf0t[$m4ac_pzocy3nw];  if( $m4ac_ss6bwxopg8 === 'select2' && $m4ac_ihnr7cyv > '' ){ $m4ac_ihnr7cyv = trim($m4ac_ihnr7cyv, ',');  if( $m4ac_pzocy3nw === 'memberships' && $m4ac_ihnr7cyv > '' ){ $m4ac_mi0uh7e29 = $this->m4ac_xehawo4dq($m4ac_ihnr7cyv); $m4ac_ihnr7cyv = $m4ac_mi0uh7e29 ? $m4ac_mi0uh7e29 : $m4ac_ihnr7cyv; $m4ac_u4tpxcro19['any_membership'] = $m4ac_mi0uh7e29 ? 1 : 0; } } if( $m4ac_pzocy3nw === 'status' ){ $m4ac_x_1654tdgb = (int)$m4ac_ihnr7cyv; } $m4ac_u4tpxcro19[$m4ac_pzocy3nw] = $m4ac_ihnr7cyv; } }  if( $m4ac_x_1654tdgb === 1 ){ $m4ac_u4tpxcro19['logged_in_only'] = 1; $m4ac_u4tpxcro19['logged_out_only'] = 0; }  else if( $m4ac_x_1654tdgb === 2 ){ $m4ac_u4tpxcro19['logged_in_only'] = 0; $m4ac_u4tpxcro19['logged_out_only'] = 1; $m4ac_u4tpxcro19 = $this->m4ac_ts0uy6vbi_o($m4ac_u4tpxcro19); }  else{ $m4ac_u4tpxcro19['logged_in_only'] = 0; $m4ac_u4tpxcro19['logged_out_only'] = 0; $m4ac_u4tpxcro19 = $this->m4ac_ts0uy6vbi_o($m4ac_u4tpxcro19); } } return $m4ac_u4tpxcro19; }  
function m4ac_ts0uy6vbi_o($m4ac_u4tpxcro19){ $m4ac_lf0da49p = apply_filters('wpal/widget/access/logged_in_settings', [ 'any_membership' => 1, 'memberships' => 1, 'tags1' => 1, 'tags2' => 1 ]); if( is_array($m4ac_lf0da49p) && ! empty($m4ac_lf0da49p) ){ foreach ($m4ac_lf0da49p as $m4ac_ukqvxo6ne7 => $m4ac_ihnr7cyv) { if( array_key_exists($m4ac_ukqvxo6ne7, $m4ac_u4tpxcro19) ){ unset($m4ac_u4tpxcro19[$m4ac_ukqvxo6ne7]); } } } return $m4ac_u4tpxcro19; }  
function m4ac_xehawo4dq($m4ac_w7xoilfczp2) { $m4ac_t3cu9hgt = explode(',', $m4ac_w7xoilfczp2); if( in_array('any_membership', $m4ac_t3cu9hgt) ) { return 'any_membership'; } else { return $m4ac_w7xoilfczp2; } } } }
