<?php
/**
* Copyright (c) 2018-2021 David J Bullock
* Web Power and Light
*/

 if (! defined( 'ABSPATH' ) ) { die(); }  if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_uk3r5g1cl_2 { protected $ext_ver = '1.0.5'; public $slug = 'beaver_builder'; public $to_json = [];  public $omitted_blocks = [];  public $ns = '';  public $prefix = '';  public $I18n = [];  public $access_class;  private 
function __construct(){} static 
function m4ac_zw_dhmca() : self { static $m4ac_u4tpxcro19 = null; if(is_null($m4ac_u4tpxcro19)){ $m4ac_u4tpxcro19 = new self; $m4ac_u4tpxcro19->access_class = m4ac_rntik2rdq0::m4ac_zw_dhmca(); $m4ac_u4tpxcro19->prefix = $m4ac_u4tpxcro19->access_class::PREFIX; $m4ac_u4tpxcro19->ns = $m4ac_u4tpxcro19->access_class::NS; $m4ac_u4tpxcro19->m4ac_w07mrqh2sxlp(); } return $m4ac_u4tpxcro19; } 
function m4ac_w07mrqh2sxlp(){  add_filter("{$this->ns}/{$this->slug}/control/config", [$this, 'm4ac_mc_s180dqj'], 10, 1); $m4ac_n_j31z9qsv = $this->access_class->m4ac_hrc7dpu9j(); $this->I18n = $m4ac_n_j31z9qsv->m4ac_up3uovdq_ib7( false, $this->slug ); $this->to_json['WPAL_BLOCKS_PREFIX'] = $this->prefix; $this->to_json['WPAL_BLOCKS_KEYS_REMOVED_TEXT'] = $this->I18n['keys_removed_text']; $this->to_json['controls'] = $m4ac_n_j31z9qsv->m4ac_buapm02l_8dx($this->slug); $this->to_json['tags'] = $m4ac_n_j31z9qsv->m4ac_ni3dn9fc();  $this->omitted_blocks = apply_filters("{$this->ns}/{$this->slug}/settings/omitted_blocks", ['col']); add_filter('fl_builder_register_settings_form', [$this, 'm4ac_q84yi5_0efq'], PHP_INT_MAX, 2 );  add_filter('fl_builder_custom_fields', [$this, 'm4ac_dd7_je0xh9'] );  add_action('wp_enqueue_scripts', [$this, 'm4ac_cihcgvtj'], PHP_INT_MAX );  }  
function m4ac_mc_s180dqj( array $m4ac_b7_c3kyi ) : array { foreach ($m4ac_b7_c3kyi as $m4ac_llc9w_f1tk6z => $m4ac_k4zrbefq2ps5) { if( $m4ac_k4zrbefq2ps5['type'] === 'checkbox' ){ $m4ac_b7_c3kyi[$m4ac_llc9w_f1tk6z]['type'] = 'wpal_blocks_toggle'; $m4ac_b7_c3kyi[$m4ac_llc9w_f1tk6z]['description'] = ''; } else if( $m4ac_k4zrbefq2ps5['type'] === 'SELECT2' ) { $m4ac_b7_c3kyi[$m4ac_llc9w_f1tk6z]['type'] = 'text'; $m4ac_b7_c3kyi[$m4ac_llc9w_f1tk6z]['class'] = 'bb-wpal-blocks-select2'; } } return $m4ac_b7_c3kyi; }  
function m4ac_dd7_je0xh9( array $m4ac_u9uhl_ci87 ) { $m4ac_u9uhl_ci87['wpal_blocks_toggle'] = trailingslashit( __DIR__ ) . 'toggle.php'; return $m4ac_u9uhl_ci87; }  
function m4ac_q84yi5_0efq( array $m4ac_sqv16detbj4_, string $m4ac_x6vpzdgl54 ) : array { $m4ac_km4i0phu = ($m4ac_x6vpzdgl54 === 'row' || $m4ac_x6vpzdgl54 === 'col');  if ($m4ac_km4i0phu) { $m4ac_sqv16detbj4_['tabs'] = isset($m4ac_sqv16detbj4_['tabs']) ? $m4ac_sqv16detbj4_['tabs'] : []; $m4ac_sqv16detbj4_['tabs']['advanced'] = ( isset($m4ac_sqv16detbj4_['tabs']['advanced']) ) ? $m4ac_sqv16detbj4_['tabs']['advanced'] : [ 'title' => __( 'Advanced', $this->ns ) ]; $m4ac_sqv16detbj4_['tabs']['advanced']['sections'] = isset($m4ac_sqv16detbj4_['tabs']['advanced']['sections']) ? $m4ac_sqv16detbj4_['tabs']['advanced']['sections'] : [];  $m4ac_sqv16detbj4_['tabs']['advanced']['sections'] = $this->m4ac_xokyrtn50($m4ac_sqv16detbj4_['tabs']['advanced']['sections'], $m4ac_x6vpzdgl54); } else {  if ($m4ac_x6vpzdgl54 === 'module_advanced') { $m4ac_sqv16detbj4_['sections'] = isset($m4ac_sqv16detbj4_['sections']) ? $m4ac_sqv16detbj4_['sections'] : []; $m4ac_sqv16detbj4_['sections'] = $this->m4ac_xokyrtn50( $m4ac_sqv16detbj4_['sections'], $m4ac_x6vpzdgl54 ); } } return $m4ac_sqv16detbj4_; }  
function m4ac_xokyrtn50( array $m4ac_erqmzg0e_o, string $m4ac_x6vpzdgl54) : array { $m4ac_oyv0lx4s = []; $m4ac_ukqvxo6ne7 = 'visibility'; if ( array_key_exists($m4ac_ukqvxo6ne7, $m4ac_erqmzg0e_o) ) { foreach ($m4ac_erqmzg0e_o as $m4ac_qbjmklz9u => $m4ac_xki0g4o7uem) { $m4ac_oyv0lx4s[$m4ac_qbjmklz9u] = $m4ac_xki0g4o7uem; if ($m4ac_qbjmklz9u === $m4ac_ukqvxo6ne7) { $m4ac_u9uhl_ci87 = $this->m4ac_hfr7ukej($m4ac_x6vpzdgl54); if ( $m4ac_u9uhl_ci87 ){ $m4ac_oyv0lx4s['wpal-blocks'] = $m4ac_u9uhl_ci87; } } } } else { $m4ac_oyv0lx4s = $m4ac_erqmzg0e_o; $m4ac_u9uhl_ci87 = $this->m4ac_hfr7ukej( $m4ac_x6vpzdgl54 ); if ($m4ac_u9uhl_ci87) { $m4ac_oyv0lx4s['wpal-blocks'] = $m4ac_u9uhl_ci87; } } return $m4ac_oyv0lx4s; }  
function m4ac_hfr7ukej( string $m4ac_x6vpzdgl54 ) {  $m4ac_se0rlu1358j = in_array($m4ac_x6vpzdgl54, $this->omitted_blocks) ? false : $this->to_json['controls']; if (! $m4ac_se0rlu1358j || empty($m4ac_se0rlu1358j) ){ return; } $m4ac_vo6741wvgc = [ 'title' => $this->I18n['settings_title'], 'fields' => [] ]; foreach ($m4ac_se0rlu1358j as $m4ac_llc9w_f1tk6z => $m4ac_k4zrbefq2ps5) { $m4ac_ss6bwxopg8 = isset($m4ac_k4zrbefq2ps5['type']) ? $m4ac_k4zrbefq2ps5['type'] : false; $m4ac_pzocy3nw = isset($m4ac_k4zrbefq2ps5['name']) ? $m4ac_k4zrbefq2ps5['name'] : false; if ($m4ac_ss6bwxopg8 && $m4ac_pzocy3nw) { $m4ac_ce1kgncadr5 = [ 'type' => $m4ac_ss6bwxopg8, 'label' => $m4ac_k4zrbefq2ps5['label'] ]; $conditional_settings = ['default', 'description', 'help', 'class', 'options', 'multi-select', 'rows', 'placeholder']; foreach ($conditional_settings as $m4ac_qbjmklz9u => $m4ac_wvedziauxc) { if ( isset( $m4ac_k4zrbefq2ps5[$m4ac_wvedziauxc] ) ){ $m4ac_ce1kgncadr5[$m4ac_wvedziauxc] = $m4ac_k4zrbefq2ps5[$m4ac_wvedziauxc]; } } $m4ac_ce1kgncadr5 = apply_filters("{$this->ns}/{$this->slug}/editor/control/args", $m4ac_ce1kgncadr5, $m4ac_pzocy3nw, $m4ac_ss6bwxopg8, $m4ac_x6vpzdgl54 ); $m4ac_vo6741wvgc['fields'][$m4ac_pzocy3nw] = $m4ac_ce1kgncadr5; } } return $m4ac_vo6741wvgc; }  
function m4ac_cihcgvtj() { if (! FLBuilderModel::is_builder_active() ) { return; } $m4ac_kkq24nui = 'wpal-blocks-bb'; $m4ac_atr94xdeg3 = plugin_dir_url( __FILE__ ); $m4ac_lkcphno6l0v1 = ['jquery', "{$m4ac_kkq24nui}_s2js"]; $this->access_class->m4ac_hrc7dpu9j()->m4ac_nu6elf21_mzn( false, $m4ac_kkq24nui ); wp_enqueue_style("{$m4ac_kkq24nui}_s2css"); wp_enqueue_script("{$m4ac_kkq24nui}_s2js"); wp_register_script("{$m4ac_kkq24nui}-editor-js", "{$m4ac_atr94xdeg3}editor.js", $m4ac_lkcphno6l0v1, $this->ext_ver, true); wp_register_style("{$m4ac_kkq24nui}-editor-css", "{$m4ac_atr94xdeg3}editor.css", false, $this->ext_ver, 'all' ); wp_enqueue_script("{$m4ac_kkq24nui}-editor-js"); wp_enqueue_style("{$m4ac_kkq24nui}-editor-css"); wp_localize_script("{$m4ac_kkq24nui}-editor-js", 'wpalbb_params', $this->to_json); } } }
