<?php
/**
 * Copyright (c) 2020 David J Bullock
 * Web Power and Light
 */

 if (! defined( 'ABSPATH' ) ) { die(); }  
class m4ac_ihjiwv3y1 { const NONCE = 'wpal/menu/access'; private $scripts_loaded = false; private $meta_fields = null; private $rendered_nonce = false;  
function m4ac_ahnzartcqlk() { if (! is_null($this->meta_fields) ) { return $this->meta_fields; } $m4ac_kbagjrq9 = WPAL_MENU_KEY_NAME; $m4ac_xnow_tahpc = WPAL_MENU_ACCESS_LEVEL_NAME; $m4ac_v4m532o6 = " " . __( "settings are only available for logged in users." ); $this->meta_fields = apply_filters('wpal/menu/fields', [ [ 'name' => 'status', 'label' => __('User Status'), 'type' => 'select2', 'data' => 'status', 'disable-search' => true, 'change' => 'wpal_menu_access_status_toggle', 'priority' => 100 ], [ 'name' => 'memberships', 'label' => $m4ac_xnow_tahpc, 'info' => $m4ac_xnow_tahpc . $m4ac_v4m532o6, 'type' => 'select2', 'data' => 'levels', 'change' => 'wpal_menu_contact_toggle', 'multiple' => 1, 'priority' => 200 ], [ 'name' => 'tags1', 'label' => $m4ac_kbagjrq9, 'info' => $m4ac_kbagjrq9 . $m4ac_v4m532o6, 'type' => 'select2', 'data' => 'keys', 'change' => 'wpal_menu_contact_toggle', 'multiple' => 1, 'priority' => 300 ], [ 'name' => 'tags2', 'label' => __("AND") . " {$m4ac_kbagjrq9}", 'info' => "The contact must have both the 1st {$m4ac_kbagjrq9} AND this {$m4ac_kbagjrq9} in order to view this item and these {$m4ac_v4m532o6}", 'type' => 'select2', 'data' => 'keys', 'change' => 'wpal_menu_contact_toggle', 'multiple' => 1, 'priority' => 400 ], [ 'name' => 'eval', 'label' => __("PHP Boolean Expression"), 'type' => 'textarea', 'desc' => __('Enter a boolean expression which evaluates to true to show or false to hide this element.'), 'priority' => 500 ], ] ); return $this->meta_fields; }  
function m4ac_rh6ijntd() { add_action('wp_nav_menu_item_custom_fields', [$this, 'm4ac_r2mygvbr'], 10, 4); add_action('wp_update_nav_menu_item', [$this, 'm4ac_q8h09es4iz'], 10, 3); add_action('admin_enqueue_scripts', [$this, 'm4ac_dndwhqu097mv']); add_filter('clean_url', [$this, 'm4ac__pf9swe0'], 99, 3 ); }  
function m4ac_dndwhqu097mv() { if ($this->scripts_loaded) { return; } $m4ac_y2mw1xc6rq = m4ac_dxe41wmltk()->m4ac_lx4jv6fi7k(); $m4ac_atr94xdeg3 = m4ac_dxe41wmltk()->m4ac_mqvgr2baz(); $m4ac_lkcphno6l0v1 = ['jquery']; wp_enqueue_style("wpal-menu-access-css", "{$m4ac_atr94xdeg3}menu.css", [], $m4ac_y2mw1xc6rq, "all"); wp_enqueue_script("wpal-menu-access-js", "{$m4ac_atr94xdeg3}menu.js", $m4ac_lkcphno6l0v1, $m4ac_y2mw1xc6rq, true);  $m4ac_qo20ti1h6 = "{$m4ac_atr94xdeg3}vendor/selectwoo/"; $m4ac_kkq24nui = "wpal-menu-access-selectwoo-"; $m4ac_oucjdq1x9_ = '1.0.1'; wp_enqueue_style("{$m4ac_kkq24nui}css", "{$m4ac_qo20ti1h6}selectwoo.css", [], $m4ac_oucjdq1x9_, "all"); wp_enqueue_script("{$m4ac_kkq24nui}js", "{$m4ac_qo20ti1h6}selectwoo.full.min.js", $m4ac_lkcphno6l0v1, $m4ac_oucjdq1x9_, true);  wp_localize_script("wpal-menu-access-js", "wpal_menu_data", [ 'select2Data' => [ 'levels' => $this->m4ac_oxvlnfdp(), 'keys' => $this->m4ac_gxlef7oam(), 'status' => $this->m4ac_l6s5zjkxm() ], 'I18n' => [ 'ids_removed' => WPAL_MENU_IDS_REMOVED_TEXT ], 'loggedInOnlyKeys' => $this->m4ac_ti4mso7bq() ]); $this->scripts_loaded = true; }  
function m4ac_oxvlnfdp() { $m4ac_b40ft1esgpw = apply_filters('wpal/menu/access_levels', [], 'nav_menu_item'); $m4ac_md7c8zsu2o = [ [ 'id' => 'any_membership', 'text' => __('Any', 'm4ac_kkt4iaow70v8') . ' ' . WPAL_MENU_ACCESS_LEVEL_NAME ] ]; if (is_array($m4ac_b40ft1esgpw) && ! empty($m4ac_b40ft1esgpw) ) { foreach ($m4ac_b40ft1esgpw as $m4ac_lj_fwoc5ub1y => $m4ac_uk4w9mfx) { $m4ac_pzocy3nw = stripslashes($m4ac_uk4w9mfx['name']); $m4ac_uk4w9mfx = $m4ac_uk4w9mfx['level']; $m4ac_md7c8zsu2o[] = [ 'id' => $m4ac_lj_fwoc5ub1y, 'text' => "{$m4ac_pzocy3nw} ({$m4ac_uk4w9mfx})" ]; } } return $m4ac_md7c8zsu2o; }  
function m4ac_gxlef7oam() { $m4ac_md7c8zsu2o = []; $m4ac_ah4c_sou = apply_filters('wpal/menu/get_key_map', [], 'nav_menu_item'); if (is_array($m4ac_ah4c_sou) && ! empty($m4ac_ah4c_sou) ) { foreach ($m4ac_ah4c_sou as $id => $text) { $m4ac_md7c8zsu2o[] = [ 'id' => $id, 'text' => $text ]; } } return $m4ac_md7c8zsu2o; } 
function m4ac_l6s5zjkxm() { return apply_filters('wpal/menu/access/user/status', [ [ 'id' => '', 'text' => __( 'All Visitors', 'm4ac_kkt4iaow70v8' ) ], [ 'id' => '1', 'text' => __( 'Logged In Users Only', 'm4ac_kkt4iaow70v8' ) ], [ 'id' => '2', 'text' => __( 'Logged Out Visitors Only', 'm4ac_kkt4iaow70v8' ) ] ] ); } 
function m4ac_ti4mso7bq(){ return apply_filters('wpal/menu/logged_in_only/fields', ['memberships', 'tags1', 'tags2'] ); }  
function m4ac_r2mygvbr($m4ac_c_0iefnwl, $m4ac_ww7oiazfdu, $m4ac_des_ngqptlbm, $m4ac_ah90o86m) { $m4ac_ld06b5vztcj = $this->m4ac_ahnzartcqlk(); if (is_array($m4ac_ld06b5vztcj) && ! empty($m4ac_ld06b5vztcj) ) { $m4ac_xurp0xnols83 = m4ac_dxe41wmltk()->m4ac_suhaylpjg($m4ac_c_0iefnwl); $m4ac_x_1654tdgb = ''; foreach ($m4ac_ld06b5vztcj as $m4ac_t365kbjxq => $m4ac_wc9s2dnt4y) { $m4ac_pzocy3nw = $m4ac_wc9s2dnt4y['name']; $m4ac_ld06b5vztcj[$m4ac_t365kbjxq]['value'] = isset($m4ac_xurp0xnols83[$m4ac_pzocy3nw]) ? $m4ac_xurp0xnols83[$m4ac_pzocy3nw] : ''; if ($m4ac_pzocy3nw === 'status' ) { $m4ac_x_1654tdgb = $m4ac_ld06b5vztcj[$m4ac_t365kbjxq]['value']; } }  if (! $this->rendered_nonce ) { $m4ac_ush6rftjk5i = self::NONCE; wp_nonce_field($m4ac_ush6rftjk5i, "_{$m4ac_ush6rftjk5i}_name"); $this->rendered_nonce = true; }  $m4ac_n5dw3y7vlku = 'wpal-menu-access'; require __DIR__ . '/templates/access-meta-fields.php'; } }  
function m4ac__pf9swe0($m4ac_atr94xdeg3, $m4ac_ue6fd1970, $m4ac_rym2fvt71) { return (m4ac_dxe41wmltk()->m4ac_fvmlp8ifo( $m4ac_ue6fd1970) ) ? $m4ac_ue6fd1970 : $m4ac_atr94xdeg3; }  
function m4ac_q8h09es4iz($m4ac_w4k6oh5c7m0f, $m4ac_c_0iefnwl, $m4ac_ah90o86m) {  $m4ac_ush6rftjk5i = self::NONCE; if (! isset($_POST["_{$m4ac_ush6rftjk5i}_name"]) || ! wp_verify_nonce($_POST["_{$m4ac_ush6rftjk5i}_name"], $m4ac_ush6rftjk5i) ) { return $m4ac_w4k6oh5c7m0f; } $m4ac_xurp0xnols83 = []; $m4ac_z273jg8t = []; $m4ac_iimr5ze_j7 = false; $m4ac_w81vfhlna = false; $m4ac_ld06b5vztcj = $this->m4ac_ahnzartcqlk(); if (is_array($m4ac_ld06b5vztcj) && ! empty($m4ac_ld06b5vztcj) ) { $m4ac_zxmlneb5 = ( isset($_POST['wpal_menu']) ) ? $_POST['wpal_menu'] : []; $m4ac_z273jg8t = m4ac_dxe41wmltk()->m4ac_suhaylpjg($m4ac_c_0iefnwl); $m4ac_iimr5ze_j7 = ( ! empty($m4ac_z273jg8t) ) ? true : false; $m4ac_xurp0xnols83 = $m4ac_z273jg8t; $m4ac_x_1654tdgb = 0;  foreach ($m4ac_ld06b5vztcj as $m4ac_t365kbjxq => $m4ac_wc9s2dnt4y) { $m4ac_pzocy3nw = $m4ac_wc9s2dnt4y['name']; $m4ac_wvedziauxc = ( isset($m4ac_zxmlneb5[$m4ac_pzocy3nw]) ) ? $m4ac_zxmlneb5[$m4ac_pzocy3nw] : []; $m4ac_ihnr7cyv = ( isset($m4ac_wvedziauxc[$m4ac_c_0iefnwl]) ) ? $m4ac_wvedziauxc[$m4ac_c_0iefnwl] : ''; $m4ac_y10xi6ef = ( isset($m4ac_z273jg8t[$m4ac_pzocy3nw]) ) ? $m4ac_z273jg8t[$m4ac_pzocy3nw] : ''; if ($m4ac_wc9s2dnt4y['type'] === 'select2' && $m4ac_ihnr7cyv > '' ) { $m4ac_ihnr7cyv = trim($m4ac_ihnr7cyv, ',');  if ($m4ac_pzocy3nw === 'memberships' && $m4ac_ihnr7cyv > '' ) { $m4ac_mi0uh7e29 = $this->m4ac_xehawo4dq($m4ac_ihnr7cyv); $m4ac_ihnr7cyv = $m4ac_mi0uh7e29 ? $m4ac_mi0uh7e29 : $m4ac_ihnr7cyv; $m4ac_xurp0xnols83['any_membership'] = $m4ac_mi0uh7e29 ? 1 : 0; } } if ($m4ac_ihnr7cyv != $m4ac_y10xi6ef ) { $m4ac_xurp0xnols83[$m4ac_pzocy3nw] = esc_attr($m4ac_ihnr7cyv); $m4ac_w81vfhlna = true; } if ($m4ac_pzocy3nw === 'status' ) { $m4ac_x_1654tdgb = (int) $m4ac_ihnr7cyv; } }  if ($m4ac_x_1654tdgb === 1) { $m4ac_xurp0xnols83['logged_in_only'] = 1; $m4ac_xurp0xnols83['logged_out_only'] = 0; }  elseif ($m4ac_x_1654tdgb === 2) { $m4ac_xurp0xnols83['logged_in_only'] = 0; $m4ac_xurp0xnols83['logged_out_only'] = 1; $m4ac_xurp0xnols83 = $this->m4ac_ts0uy6vbi_o($m4ac_xurp0xnols83); }  else{ $m4ac_xurp0xnols83['logged_in_only'] = 0; $m4ac_xurp0xnols83['logged_out_only'] = 0; $m4ac_xurp0xnols83 = $this->m4ac_ts0uy6vbi_o($m4ac_xurp0xnols83); } } if ($m4ac_w81vfhlna) { $m4ac_x6vpzdgl54 = m4ac_dxe41wmltk()->m4ac_mt32ozh9();  if (! array_filter($m4ac_xurp0xnols83) ) {  if ($m4ac_iimr5ze_j7) { delete_post_meta($m4ac_c_0iefnwl, $m4ac_x6vpzdgl54); } }  else{ update_post_meta($m4ac_c_0iefnwl, $m4ac_x6vpzdgl54, $m4ac_xurp0xnols83); } } }  
function m4ac_ts0uy6vbi_o($m4ac_xurp0xnols83) { $m4ac_lf0da49p = apply_filters('wpal/menu/access/logged_in_settings', [ 'any_membership' => 1, 'memberships' => 1, 'tags1' => 1, 'tags2' => 1 ]); if (is_array($m4ac_lf0da49p) && ! empty($m4ac_lf0da49p) ) { foreach ($m4ac_lf0da49p as $m4ac_ukqvxo6ne7 => $m4ac_ihnr7cyv) { if (array_key_exists($m4ac_ukqvxo6ne7, $m4ac_xurp0xnols83) ) { unset($m4ac_xurp0xnols83[$m4ac_ukqvxo6ne7]); } } } return $m4ac_xurp0xnols83; }  
function m4ac_xehawo4dq($m4ac_w7xoilfczp2) { $m4ac_t3cu9hgt = explode(',', $m4ac_w7xoilfczp2); return in_array('any_membership', $m4ac_t3cu9hgt) ? 'any_membership' : $m4ac_w7xoilfczp2; }  private 
function __construct() { }  static 
function m4ac_y5ges3afo() { static $m4ac_u4tpxcro19 = false; if (! $m4ac_u4tpxcro19) { $m4ac_u4tpxcro19 = new self; } return $m4ac_u4tpxcro19; } }
