<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { if (! defined('MEMBERIUM_TELEMETRY') ) {  
function m4ac_k46mynsp9dh(int $m4ac_z951hab0oj6, string $m4ac_oig37kxo, string $m4ac_q7vmeliqf, int $m4ac_iv0wjmprc, string $m4ac_l9ep6jcf) {  if (isset($m4ac_l9ep6jcf[0]['function']) ) { if (in_array($m4ac_l9ep6jcf[0]['function'], ['m4ac_vn9deax1brm', 'm4ac_a1tdoe03b']) ) { array_shift($m4ac_l9ep6jcf); } } $m4ac_q7vmeliqf = substr($m4ac_q7vmeliqf, strlen(WP_PLUGIN_DIR) ); $m4ac_pelnu35zw0s = implode(':', ['M4AC', memberium_app()->m4ac_lx4jv6fi7k(), hash('crc32b', $m4ac_q7vmeliqf), $m4ac_iv0wjmprc, $m4ac_z951hab0oj6]); $m4ac_n2xb45kfup = 'telemetry::' . $m4ac_pelnu35zw0s; $m4ac_v6hfp2j9d = get_transient($m4ac_n2xb45kfup); if ($m4ac_v6hfp2j9d === false) { set_transient($m4ac_n2xb45kfup, time(), 60 * 60 * 24 * 365); $m4ac_at_5xofh = function_exists('get_current_user_id') ? get_current_user_id() : 0; $m4ac_md7c8zsu2o = [ 'sku' => 'M4AC', 'site_url' => get_site_url(), 'page_url' => $_SERVER['REQUEST_URI'], 'user_id' => $m4ac_at_5xofh, 'ip_address' => $_SERVER['REMOTE_ADDR'], 'php_version' => phpversion(), 'message_type' => 'error', 'guid' => $m4ac_pelnu35zw0s, 'errno' => $m4ac_z951hab0oj6, 'errstr' => $m4ac_oig37kxo, 'errfile' => $m4ac_q7vmeliqf, 'errline' => $m4ac_iv0wjmprc, 'stack' => $m4ac_l9ep6jcf, ]; $m4ac_md7c8zsu2o = json_encode($m4ac_md7c8zsu2o); $m4ac_w6cdrpiqox38 = curl_init('https://telemetry.webpowerandlight.com/memberium/'); curl_setopt($m4ac_w6cdrpiqox38, CURLOPT_CUSTOMREQUEST, 'POST'); curl_setopt($m4ac_w6cdrpiqox38, CURLOPT_POSTFIELDS, $m4ac_md7c8zsu2o); curl_setopt($m4ac_w6cdrpiqox38, CURLOPT_RETURNTRANSFER, true); curl_setopt($m4ac_w6cdrpiqox38, CURLOPT_HTTPHEADER, [ 'Content-Type: application/json', 'Content-Length: ' . strlen($m4ac_md7c8zsu2o) ] ); $m4ac_fic2e07vfkz = curl_exec($m4ac_w6cdrpiqox38); } if (MEMBERIUM_DEBUG && memberium_app()->m4ac_k6b8c0f7g5() ) { echo 'Error Number: ', $m4ac_z951hab0oj6, '<br>'; echo 'GUID: ', $m4ac_pelnu35zw0s, '<br>'; echo 'Error: ', $m4ac_oig37kxo, '<br>'; echo 'File: ', $m4ac_q7vmeliqf, '<br>'; echo 'Line: ', $m4ac_iv0wjmprc, '<br>'; die(); } return true; } 
function m4ac_a1tdoe03b(int $m4ac_z951hab0oj6, string $m4ac_oig37kxo, string $m4ac_q7vmeliqf, int $m4ac_iv0wjmprc, string $m4ac_l9ep6jcf) { if (false === stripos($m4ac_q7vmeliqf, '/memberium-ac/') ) { return true; }  m4ac_k46mynsp9dh($m4ac_z951hab0oj6, $m4ac_oig37kxo, $m4ac_q7vmeliqf, $m4ac_iv0wjmprc, $m4ac_l9ep6jcf); return true; } 
function m4ac_vn9deax1brm() { if ($m4ac_cc39jsy5 = error_get_last() ) { if (false === stripos($m4ac_cc39jsy5['file'], '/memberium-ac/') ) { return true; } $m4ac_szy8hqx0 = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT); m4ac_k46mynsp9dh($m4ac_cc39jsy5['type'], $m4ac_cc39jsy5['message'], $m4ac_cc39jsy5['file'], $m4ac_cc39jsy5['line'], $m4ac_szy8hqx0); } return true; }  set_error_handler('m4ac_a1tdoe03b', E_ALL); register_shutdown_function('m4ac_vn9deax1brm'); define('MEMBERIUM_TELEMETRY', 1); } }
