<?php
/**
* Copyright (c) 2018-2021 David J Bullock
* Web Power and Light
*/

 if (! defined('ABSPATH') ) { die(); } if (class_exists('m4ac_f5ovcw_1iln') ) { 
class m4ac_y82nyi9t { private static 
function m4ac_l_68st1h7() { echo '<p>You can set your login options below but even though you can do some cool stuff, none of them are required to launch your site.</p>'; echo '<form method="POST" action="">'; echo '<ul>'; wp_nonce_field(MEMBERIUM_MODULES_DIR, 'memberium_options_nonce'); } private static 
function m4ac_p52gu_ntq() { $m4ac_hix162sdofjr = memberium_app()->m4ac_x280qrz9kmic('password_field'); $m4ac_tcskp7250q = memberium_app()->m4ac_x280qrz9kmic('secure_password_sync'); $m4ac_qd9rwc_as4 = (int) memberium_app()->m4ac_x280qrz9kmic('secure_sync_automation'); $m4ac_f06hmeg4j = (int) memberium_app()->m4ac_x280qrz9kmic('min_password_length'); echo '<h3>Password Settings</h3>'; echo '<li><label>CRM Plaintext Password Field</label>'; echo '<select id="password_field" name="password_field" class="basic-single" style="width:250px;">'; echo '<option value="">(None)</option>'; foreach (self::$m4ac_ag8v_3eu1z as $m4ac_wc9s2dnt4y) { $m4ac_x2yxklc6q3_p = ($m4ac_hix162sdofjr == $m4ac_wc9s2dnt4y['tag']) ? ' selected ' : ''; echo '<option value="', $m4ac_wc9s2dnt4y['tag'], '" ', $m4ac_x2yxklc6q3_p, '>', $m4ac_wc9s2dnt4y['name'], '</option>'; } echo '</select>', m4ac_s126v0fexga::m4ac_e_rxkt9u(1171), '</li>'; echo '<li><label>CRM Secure Password Sync Field</label>'; echo '<select id="secure_password_sync" name="secure_password_sync" class="basic-single" style="width:250px;">'; echo '<option value="">(None)</option>'; foreach (self::$m4ac_ag8v_3eu1z as $m4ac_wc9s2dnt4y) { $m4ac_x2yxklc6q3_p = ($m4ac_tcskp7250q == $m4ac_wc9s2dnt4y['id']) ? ' selected ' : ''; echo '<option value="', $m4ac_wc9s2dnt4y['id'], '" ', $m4ac_x2yxklc6q3_p, '>', $m4ac_wc9s2dnt4y['name'], '</option>'; } echo '</select>', m4ac_s126v0fexga::m4ac_e_rxkt9u(16065), ' This must be a different field than the password field</li>'; echo '<li><label>Secure Password Sync Automation</label>'; echo '<input value="', $m4ac_qd9rwc_as4, '" id="secure_sync_automation" type="hidden" class="dropdown automationdropdown" name="secure_sync_automation">'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(16067), '</li>'; $m4ac_ah90o86m = [ 'label' => 'Minimum Password Length', 'placeholder' => '0-64', 'value' => $m4ac_f06hmeg4j, 'help_id' => 1185, 'type' => 'number', 'size' => 20, 'style' => 'width:80px;', 'custom' => [ 'min' => 0, 'max' => 64, 'step' => 1 ], ]; echo self::$m4ac__uo0fets->m4ac_qm47in38u('min_password_length', $m4ac_ah90o86m); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Send WordPress Welcome Email', 'wp_welcome_email', 16134); } private static 
function m4ac_e20qn3js() { $m4ac_em6hrqja = (int) memberium_app()->m4ac_x280qrz9kmic('maximum_login_ips'); $m4ac_hg8rb24d = (int) memberium_app()->m4ac_x280qrz9kmic('maximum_login_timeframe'); $m4ac_fwtp4v0kf = (string) memberium_app()->m4ac_x280qrz9kmic('site_ban_tag'); echo '<hr>'; echo '<h3>Login Restrictions</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Require Membership', 'require_membership', 1202); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Prevent Simultaneous Logins', 'simultaneous_logins', 1197); echo '<li><label>Maximum Login IPs</label>'; echo '<input type="number" id="maximum_login_ips" name="maximum_login_ips" min="0" max="256" size="3" step="1" value="', $m4ac_em6hrqja, '" >'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(1204), '</li>'; echo '<li><label>Maximum Login Window (Hours)</label>'; echo '<input type="number" id="maximum_login_timeframe" name="maximum_login_timeframe" min="0" max="256" size="3" step="1" value="', $m4ac_hg8rb24d, '" >'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(1206), '</li>'; $m4ac_ah90o86m = [ 'label' => 'Site Ban Tag', 'value' => $m4ac_fwtp4v0kf, 'style' => 'width:200px;', 'class' => 'dropdown taglistdropdown', 'help_id' => 1195, 'help_text' => null, ]; self::$m4ac__uo0fets->m4ac_qm47in38u('site_ban_tag', $m4ac_ah90o86m); echo self::$m4ac__uo0fets->m4ac_y8eiblpogh('Autologout/Inactivity Timer', 'autologout_time', 'number', 0, 'min="0" style="text-align:right;width:80px;" ', '', 7688); } private static 
function m4ac_rt18od0kp() { $m4ac_iaqt8lemp3 = trim( memberium_app()->m4ac_x280qrz9kmic('loginlog_whitelist') ); echo '<hr>'; echo '<h3>Login Logging</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Login Log', 'login_log', 1187); echo '<li><label>Login Log IP Whitelist</label>'; echo '<input type="text" id="loginlog_whitelist" name="loginlog_whitelist" value="', $m4ac_iaqt8lemp3, '" size="50">'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(21577), '</li>'; } private static 
function m4ac_smi9tk4wn3sy() { $m4ac_ef3t9z7a8 = (int) memberium_app()->m4ac_x280qrz9kmic('login_url'); $m4ac_nokx60vpizu = (int) memberium_app()->m4ac_x280qrz9kmic('login_automation'); $m4ac_ktuqrm97lh = (int) memberium_app()->m4ac_x280qrz9kmic('logout_automation'); echo '<hr>'; echo '<h3>Login Actions</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable Login Sync (Turbo Mode)', 'disable_login_sync', 15967); echo '<li><label for="login_url">Login Page</label>'; echo '<input value="', $m4ac_ef3t9z7a8, '" type="hidden" id="login_url" name="login_url" class="dropdown pagelistdropdown">'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(1208), '</li>'; echo '<li><label>Login Automation</label>'; echo '<input value="', $m4ac_nokx60vpizu, '" id="login_automation" type="hidden" class="dropdown automationdropdown" name="login_automation">'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(1175), '</li>'; echo '<li><label>Logout Automation</label><input id="logout_automation" type="hidden" class="dropdown automationdropdown" value="', $m4ac_ktuqrm97lh, '" name="logout_automation">'; echo m4ac_s126v0fexga::m4ac_e_rxkt9u(1178), '</li>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable Display Name Update', 'disable_displayname_update', 9634); echo self::$m4ac__uo0fets->m4ac_y8eiblpogh('Display Name Format', 'displayname_format', 'text', '', ' size="40" ', '', 5731); } private static 
function m4ac_uu8bv0p7o() { $m4ac_brfyp4t0x6o = memberium_app()->m4ac_x280qrz9kmic('allow_autologin'); $m4ac_vi3a9n2f = memberium_app()->m4ac_x280qrz9kmic('autologin_authkeys'); $m4ac_vi3a9n2f = empty($m4ac_vi3a9n2f) ? wp_generate_password(12, false, false) : $m4ac_vi3a9n2f; memberium_app()->m4ac_vlpfetc4son5($m4ac_vi3a9n2f, 'autologin_authkeys'); echo '<hr>'; echo '<h3>AutoLogin Settings</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Allow Autologin', 'allow_autologin', 4398); if (! empty($m4ac_brfyp4t0x6o) ) { echo self::$m4ac__uo0fets->m4ac_y8eiblpogh('Autologin Auth Keys', 'autologin_authkeys', 'text', '', ' style="text-align:left;width:350px;" ', '', 2571); } } private static 
function m4ac_tj0b3nzp2q7l() { echo '<hr>'; echo '</ul>'; echo '<p><input type="submit" value="Update" class="button-primary"></p>'; echo '</form>'; } private static 
function m4ac_xh3z_b5urs() { global $wpdb; $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_FIELDS; $m4ac_h57xqitcp = memberium_app()->m4ac_bztk3xj1(); $m4ac_xtcz6bi97flk = "SELECT `id`, `name`, `tag` FROM `{$m4ac_jouqjei9gbc3}` WHERE `appname` = '{$m4ac_h57xqitcp}' AND `type` IN ('text', 'hidden') ORDER BY name ASC"; return $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); } private static 
function m4ac_w07mrqh2sxlp() { self::$m4ac__uo0fets = m4ac_f5ovcw_1iln::m4ac_zw_dhmca(); self::$m4ac_ag8v_3eu1z = self::m4ac_xh3z_b5urs(); } static 
function m4ac_lgfsc19jo3_r() { self::m4ac_w07mrqh2sxlp(); self::m4ac_l_68st1h7(); self::m4ac_p52gu_ntq(); self::m4ac_e20qn3js(); self::m4ac_rt18od0kp(); self::m4ac_smi9tk4wn3sy(); self::m4ac_uu8bv0p7o(); self::m4ac_tj0b3nzp2q7l(); } private 
function __construct() {} private static $m4ac_ag8v_3eu1z = []; private static $m4ac__uo0fets = null; } m4ac_y82nyi9t::m4ac_lgfsc19jo3_r(); }
