<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_f5ovcw_1iln') ) { 
class m4ac_ixv8pkc3hr { static 
function m4ac_ascga8po7ixl() { echo '<hr>'; echo '<h3>User Maintenance Actions</h3>'; $m4ac_ixk70t23_ = (int) memberium_app()->m4ac_x280qrz9kmic('user_deleted_tag'); $m4ac_ah90o86m = [ 'label' => 'User Deleted Tag (Pro+)', 'value' => $m4ac_ixk70t23_, 'style' => 'width:200px;', 'class' => 'dropdown taglistdropdown', 'help_id' => 0000, 'help_text' => null, 'disabled' => ! self::$m4ac_uqjcfvd4i, ]; self::$m4ac__uo0fets->m4ac_qm47in38u('user_deleted_tag', $m4ac_ah90o86m); $m4ac_q8shjz31rqu = (int) memberium_app()->m4ac_x280qrz9kmic('gdpr_deleted_tag'); $m4ac_ah90o86m = [ 'label' => 'GDPR Delete Tag (Pro+)', 'value' => $m4ac_q8shjz31rqu, 'style' => 'width:200px;', 'class' => 'dropdown taglistdropdown', 'help_id' => 0000, 'help_text' => null, 'disabled' => ! self::$m4ac_uqjcfvd4i, ]; self::$m4ac__uo0fets->m4ac_qm47in38u('gdpr_deleted_tag', $m4ac_ah90o86m); } static 
function m4ac_ufl6uygnwpv() { echo '<hr />'; echo '<h3>New User Registration</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Sync new Registrations to ActiveCampaign', 'sync_new_users', 0000); $m4ac_ah90o86m = [ 'label' => 'New User Registration Tag', 'value' => (string) memberium_app()->m4ac_x280qrz9kmic('new_user_registration_tag'), 'style' => 'width:200px;', 'class' => 'dropdown taglistdropdown', 'help_id' => 0000, 'help_text' => null, ]; self::$m4ac__uo0fets->m4ac_qm47in38u('new_user_registration_tag', $m4ac_ah90o86m); } static 
function m4ac_wnbekd6r5soj() { echo '<h3>Site Restrictions</h3>'; echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Site Lock', 'site_lock_enabled', 8354); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable RSS Feeds', 'protect_feeds', 1214); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable Lost Password', 'disable_lost_password', 4422); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable Password Reset', 'disable_password_reset', 4421); echo self::$m4ac__uo0fets->m4ac_l1fpox937i8d('Disable Clickjacking Protection', 'disable_xframe', 23007); $m4ac_fvwzlkf8hjxc = self::$m4ac__uo0fets->m4ac_x2v0_pogyrd9(); $m4ac_ah90o86m = [ 'label' => 'WordPress Dashboard', 'id' => 'wpadmin_role', 'value' => array_filter( explode( ',', memberium_app()->m4ac_x280qrz9kmic('wpadmin_role') ) ), 'style' => 'width:400px; height:1em !important;', 'multiple' => true, 'class' => 'roles-selector', 'help_id' => 16102, 'options' => $m4ac_fvwzlkf8hjxc, ]; self::$m4ac__uo0fets->m4ac_rrsf4v236k('wpadmin_role[]', $m4ac_ah90o86m); $m4ac_ah90o86m = [ 'label' => 'Title Bar Access', 'id' => 'titlebar_role', 'value' => array_filter(explode(',', memberium_app()->m4ac_x280qrz9kmic('titlebar_role') )), 'style' => 'width:400px; height:1em !important;', 'multiple' => true, 'class' => 'roles-selector', 'help_id' => 16104, 'options' => $m4ac_fvwzlkf8hjxc ]; self::$m4ac__uo0fets->m4ac_rrsf4v236k('titlebar_role[]', $m4ac_ah90o86m); } static 
function m4ac_lgfsc19jo3_r() { self::$m4ac__uo0fets = m4ac_f5ovcw_1iln::m4ac_zw_dhmca(); self::$m4ac_uqjcfvd4i = in_array('unlimited', m4ac_tl5skz6cfptr::m4ac_s8n7dqso_() ); echo '<form method="POST" action="">'; wp_nonce_field(MEMBERIUM_MODULES_DIR, 'memberium_options_nonce'); echo '<ul>'; self::m4ac_wnbekd6r5soj(); self::m4ac_ufl6uygnwpv(); self::m4ac_ascga8po7ixl(); echo '</ul>'; echo '<p><input type="submit" value="Update" class="button-primary"></p>'; echo '</form>'; } private 
function __construct() {} static $m4ac__uo0fets = null; static $m4ac_uqjcfvd4i = false; } m4ac_ixv8pkc3hr::m4ac_lgfsc19jo3_r(); }
