<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_f5ovcw_1iln') ) { 
function m4ac_navg7yz9t1() { $m4ac_xih84og7 = isset( $_SERVER['REQUEST_SCHEME'] ) ? $_SERVER['REQUEST_SCHEME'] : ''; return str_ireplace('http://', $m4ac_xih84og7 . '://', get_bloginfo('url') ); } 
function m4ac__5fieqh7ov() {  echo '<h3>Example Autologin Link</h3>'; $m4ac_vi3a9n2f = memberium_app()->m4ac_x280qrz9kmic('autologin_authkeys'); $m4ac_brfyp4t0x6o = memberium_app()->m4ac_x280qrz9kmic('allow_autologin'); $m4ac_ycuzemr0nld = m4ac_navg7yz9t1(); $m4ac_vi3a9n2f = empty($m4ac_vi3a9n2f) ? wp_generate_password(12, false, false) : $m4ac_vi3a9n2f; memberium_app()->m4ac_ixckjpb5(); if ($m4ac_vi3a9n2f > '' && $m4ac_brfyp4t0x6o) { echo '<div style="margin-left:25px;">'; echo '<b>Here are a few examples of common functions using your Auth Keys:</b><br />'; $m4ac_gy9lj2me1 = explode(',', $m4ac_vi3a9n2f); $m4ac_sjg82y059mf = m4ac_s126v0fexga::m4ac_e_rxkt9u(363); foreach ($m4ac_gy9lj2me1 as $m4ac_src0j6_vo7z) { $m4ac_src0j6_vo7z = urlencode($m4ac_src0j6_vo7z); $url = "{$m4ac_ycuzemr0nld}/?memb_autologin=yes&auth_key={$m4ac_src0j6_vo7z}&id=%SUBSCRIBERID%&email=%EMAIL%"; echo '<p><b>Email Autologin Example:</b> <input type="text" disabled="disabled" style="color:#000;" value="' . $url . '" size="80">', $m4ac_sjg82y059mf; } echo '</div>'; } else { echo '<p><b>Please create your auth keys to enable functionality.</b></p>'; } } 
function m4ac_pk6c8n5b_zi() { $m4ac_ad7ts3eo2g = memberium_app()->m4ac_x280qrz9kmic('http_post_key'); echo '<h3>Webhook Setup</h3>'; if (! empty($m4ac_ad7ts3eo2g) ) { $m4ac_gy9lj2me1 = explode(',', $m4ac_ad7ts3eo2g); $m4ac_ycuzemr0nld = m4ac_navg7yz9t1(); $m4ac_n2kqiyparg5 = m4ac_s126v0fexga::m4ac_e_rxkt9u(10689); echo "<div style='margin-left:25px;'>"; foreach ($m4ac_gy9lj2me1 as $m4ac_src0j6_vo7z) { $m4ac_src0j6_vo7z = urlencode($m4ac_src0j6_vo7z); $m4ac_atr94xdeg3 = "{$m4ac_ycuzemr0nld}/?job=createuser&key={$m4ac_src0j6_vo7z}"; echo "<p><b>Password Generator Example:</b> <input type='text' value='{$m4ac_atr94xdeg3}' size='80' disabled='disabled' style='color:#000;'>{$m4ac_n2kqiyparg5}</p>"; } $m4ac_n2kqiyparg5 = m4ac_s126v0fexga::m4ac_e_rxkt9u(10261); foreach ($m4ac_gy9lj2me1 as $m4ac_src0j6_vo7z) { $m4ac_src0j6_vo7z = urlencode($m4ac_src0j6_vo7z); $m4ac_atr94xdeg3 = "{$m4ac_ycuzemr0nld}/?type=contact&key={$m4ac_src0j6_vo7z}"; echo "<p><b>Update Contact Example:</b> <input type='text' value='{$m4ac_atr94xdeg3}' size='80' disabled='disabled' style='color:#000;'>{$m4ac_n2kqiyparg5}</p>"; } echo '</div>'; } else { echo '<p><b>Please create your "Web Hook Auth Keys" in the screen above to enable secure web hook functionality.</b></p>'; } } 
function m4ac_f4kevdl1m() { $m4ac__t4uq6xr = (int) memberium_app()->m4ac_x280qrz9kmic('default_reglink_tag'); $m4ac_n2kqiyparg5 = m4ac_s126v0fexga::m4ac_e_rxkt9u(9289); echo '<h3>Registration Link</h3>'; echo '<li><label for="default_reglink_tag">Default Registration Link Tag</label>'; echo '<input value="', $m4ac__t4uq6xr, '" type="hidden" id="default_reglink_tag" name="default_reglink_tag" class="dropdown taglistdropdown">'; echo $m4ac_n2kqiyparg5, '</li>'; } 
function m4ac_wcjutokw() { $m4ac__uo0fets = m4ac_f5ovcw_1iln::m4ac_zw_dhmca(); $m4ac_ad7ts3eo2g = memberium_app()->m4ac_x280qrz9kmic('http_post_key', ''); $m4ac_ad7ts3eo2g = empty($m4ac_ad7ts3eo2g) ? wp_generate_password(12, false, false) : $m4ac_ad7ts3eo2g; memberium_app()->m4ac_vlpfetc4son5($m4ac_ad7ts3eo2g, 'http_post_key'); echo '<h3>Webhook Setup</h3>'; echo $m4ac__uo0fets->m4ac_y8eiblpogh('Web Hook Auth Keys', 'http_post_key', 'text', '', ' style="text-align:left;width:350px;" ', '', 16124); echo $m4ac__uo0fets->m4ac_l1fpox937i8d('Webhook Log', 'event_log_webhooks', 16128); } 
function m4ac_ypry1zqg() { $m4ac__uo0fets = m4ac_f5ovcw_1iln::m4ac_zw_dhmca(); echo '<h3>Secret Keys</h3>'; echo $m4ac__uo0fets->m4ac_y8eiblpogh('ThriveCart Secret Key', 'thrivecart_secret', 'text', '', ' style="text-align:left;width:200px;" ', '', 16130);   } 
function m4ac_df6cny7g() { $m4ac_xih84og7 = isset($_SERVER['REQUEST_SCHEME']) ? $_SERVER['REQUEST_SCHEME'] : ''; $m4ac_ycuzemr0nld = str_ireplace('http://', $m4ac_xih84og7 . '://', get_bloginfo('url') ); $m4ac_gy9lj2me1 = explode(',', memberium_app()->m4ac_x280qrz9kmic('autologin_authkeys') ); $m4ac_sjg82y059mf = m4ac_s126v0fexga::m4ac_e_rxkt9u(16246); echo '<h3>New User Confirmation Links</h3>'; echo '<div style="margin-left:25px;">'; foreach ($m4ac_gy9lj2me1 as $m4ac_src0j6_vo7z) { $url = $m4ac_ycuzemr0nld . '/?action=confirmregistration&authkey=' . $m4ac_src0j6_vo7z . '&email=%EMAIL%&cid=%SUBSCRIBERID%'; echo '<p><strong>Confirmation Link Example:</strong> '; echo '<input type="text" value="' . $url . '" size="80" disabled="disabled" style="color:#000;">', $m4ac_sjg82y059mf; } echo '</div>'; } memberium_app()->m4ac_fuen6oxg('view_http_post'); echo '<form method="POST" action="">'; wp_nonce_field(MEMBERIUM_MODULES_DIR, 'memberium_options_nonce'); echo '<ul>'; m4ac_f4kevdl1m(); echo '<hr>'; m4ac_wcjutokw(); echo '<hr>'; m4ac_ypry1zqg(); echo '<hr>'; echo '<p><input type="submit" value="Update" class="button-primary"></p>'; m4ac_df6cny7g(); m4ac__5fieqh7ov(); m4ac_pk6c8n5b_zi(); echo '</ul>'; echo '</form>'; }
