<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_f5ovcw_1iln')) { 
class m4ac_pafgodtnqx9e { private static 
function m4ac_y0wfktz6u() { global $wpdb; $table = MEMBERIUM_DB_EVENTS; $appname = memberium_app()->m4ac_bztk3xj1(); $where = ''; $limit = empty($_GET['limit']) ? 15 : (int) trim($_GET['limit']); $start = empty($_GET['start']) ? 0 : (int) trim($_GET['start']); $search = empty($_GET['search']) ? '' : trim ($_GET['search']); $ipaddress = empty($_GET['ip']) ? '' : trim($_GET['ip']); $where .= empty($search) ? '' : " AND `log` LIKE '%" . $wpdb->esc_like($search) . "%' "; $where .= empty($ipaddress) ? '' : " AND `ipaddress` LIKE '%" . $wpdb->esc_like($ipaddress) . "%' "; $m4ac_xtcz6bi97flk = "SELECT `time`, `ipaddress`, `contactid`, `log` FROM `{$table}` WHERE `type` = 'loginfail' AND `appname` = '{$appname}' {$where} ORDER BY `id` DESC LIMIT {$limit} ;"; return $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); } private static 
function m4ac_um12jlop8() { $search = isset($_GET['search']) ? $_GET['search'] : ''; $ipaddress = isset($_GET['ipaddress']) ? $_GET['ipaddress'] : ''; $limit = isset($_GET['limit']) ? $_GET['limit'] : ''; echo '<form method="get" style="margin-top:12px;display:inline-block;">'; echo '<input type="hidden" name="page" value="memberium-logs">'; echo '<p><input type="hidden" name="tab" value="loginfail">'; echo "Search: <input type='text' name='search' value='{$search}' placeholder='Search'>"; echo "IP Address: <input type='text' name='ip' value='{$ipaddress}' placeholder='IP Address'>"; echo "Limit: <input type='text' name='limit' value='{$ipaddress}' placeholder='# Results'>"; echo '<input type="submit" value="Search" class="button-primary" style="margin-left:15px;"></p>'; echo '</form>'; echo '<form method="post">'; echo '<p><input type="submit" name="logpurge" value="Delete Log" class="button delete"></p>'; echo '</form>'; } private static 
function m4ac_sseo86cw4() { $m4ac_eq_dxn0rf438 = date_default_timezone_get(); $m4ac_gp0j5q_oc = get_option('timezone_string', 'UTC'); $m4ac_x_1sx47rpefc = self::m4ac_y0wfktz6u(); if (! is_array($m4ac_x_1sx47rpefc) || empty($m4ac_x_1sx47rpefc) ) { echo '<p>The Login Failure log is empty.</p>'; } else { echo '<table class="widefat">'; echo '<tr>'; echo '<td width="175">Login Time</td>'; echo '<td width="125">IP Address</td>';  echo '<td>Log</td>'; echo '</tr>'; foreach($m4ac_x_1sx47rpefc as $m4ac_lsxa90fgqk) { date_default_timezone_set('UTC'); $m4ac_dlc_ik9h6x = strtotime($m4ac_lsxa90fgqk['time']); date_default_timezone_set($m4ac_gp0j5q_oc); $m4ac__ndczilub = date('Y-m-d H:i:s', $m4ac_dlc_ik9h6x); echo '<tr>';  echo '<td>', $m4ac__ndczilub, '</td>'; echo '<td>', $m4ac_lsxa90fgqk['ipaddress'], '</td>';  echo '<td>', $m4ac_lsxa90fgqk['log'], '</td>'; echo '</tr>'; } echo '</table>'; echo "<p>Timezone: {$m4ac_gp0j5q_oc}</p>"; } date_default_timezone_set($m4ac_eq_dxn0rf438); self::m4ac_um12jlop8(); } static 
function m4ac__w5qavdh8() { global $wpdb; $table = MEMBERIUM_DB_EVENTS; $m4ac_xtcz6bi97flk = "DELETE FROM `{$table}` WHERE `type` = 'loginfail';"; $wpdb->query($m4ac_xtcz6bi97flk); wp_cache_delete('menu_logcount', 'memberiumac/admin'); } static 
function m4ac_lgfsc19jo3_r() { if (current_user_can('manage_options') ) { if ($_SERVER['REQUEST_METHOD'] == 'POST') { if (! empty($_POST['logpurge']) ) { self::m4ac__w5qavdh8(); } } self::m4ac_sseo86cw4(); } } private 
function __construct() {} } m4ac_pafgodtnqx9e::m4ac_lgfsc19jo3_r(); }
