<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_f5ovcw_1iln')) { 
class m4ac_d20xedlpo { private static 
function m4ac__w5qavdh8() { global $wpdb; $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_xtcz6bi97flk = "DELETE FROM `{$m4ac_jouqjei9gbc3}` WHERE `type` = 'autologin';"; $wpdb->query($m4ac_xtcz6bi97flk); wp_cache_delete('menu_logcount', 'memberiumac/admin'); } private static 
function m4ac_qz527n_f9() { global $wpdb; $m4ac_jouqjei9gbc3 = MEMBERIUM_DB_EVENTS; $m4ac_lmfaycbp_ot = empty($_GET['limit']) ? 5 : (int) $_GET['limit']; $m4ac_dvrhd74l8u = empty($_GET['start']) ? 0 : (int) $_GET['start']; $m4ac_uo08x_g7 = empty($_GET['contact_id']) ? 0 : (int) $_GET['contact_id']; $m4ac_frgeo10l5y = empty($_GET['textsearch']) ? '' : sanitize_text_field($_GET['textsearch']); $m4ac_ofd6sp_0 = ''; if ($m4ac_uo08x_g7) { $m4ac_ofd6sp_0 .= " AND `contactid` = {$m4ac_uo08x_g7} "; } if (! empty($m4ac_frgeo10l5y)) { $m4ac_ofd6sp_0 .= " AND (`ipaddress` LIKE '%{$m4ac_frgeo10l5y}%' OR `log` LIKE '%{$m4ac_frgeo10l5y}%' ) "; } $m4ac_xtcz6bi97flk = "SELECT `id`, `time`, `ipaddress`, `contactid`, `log` FROM `{$m4ac_jouqjei9gbc3}` WHERE `type` = 'autologin' {$m4ac_ofd6sp_0} ORDER BY `id` DESC LIMIT {$m4ac_lmfaycbp_ot} ;"; return $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); } private static 
function m4ac_sseo86cw4() { global $wpdb; $m4ac_x_1sx47rpefc = self::m4ac_qz527n_f9(); $m4ac_uo08x_g7 = empty($_GET['contact_id']) ? 0 : (int) $_GET['contact_id']; $m4ac_lmfaycbp_ot = empty($_GET['limit']) ? 5 : (int) $_GET['limit']; $m4ac_frgeo10l5y = empty($_GET['textsearch']) ? '' : $_GET['textsearch']; if (! is_array($m4ac_x_1sx47rpefc) || empty($m4ac_x_1sx47rpefc) ) { echo '<p>The Autologin log is empty.</p>'; } else { echo '<table class="widefat">'; echo '<tr>'; echo '<td width="150">Time</td>'; echo '<td width="100">IP Address</td>'; echo '<td width="100">Contact ID</td>'; echo '<td>Results</td>'; echo '</tr>'; foreach($m4ac_x_1sx47rpefc as $m4ac_lsxa90fgqk) { echo '<tr>'; echo '<td>', $m4ac_lsxa90fgqk['time'], '</td>'; echo '<td>', $m4ac_lsxa90fgqk['ipaddress'], '</td>'; echo '<td>', $m4ac_lsxa90fgqk['contactid'], '</td>'; echo '<td>', nl2br($m4ac_lsxa90fgqk['log']), '</td>'; echo '</tr>'; } echo '</table>'; } echo '<form method="get" style="margin-top:12px;">'; echo '<input type="hidden" name="page" value="memberium-logs">'; echo '<input type="hidden" name="tab" value="autologin">'; echo "Contact ID: <input type='text' name='contact_id' value='{$m4ac_uo08x_g7}' placeholder='Username'>"; echo "Search: <input type='text' name='textsearch' value='{$m4ac_frgeo10l5y}' placeholder='Text'>"; echo "Limit: <input type='text' name='limit' value='{$m4ac_lmfaycbp_ot}' placeholder='# Results'>"; echo '<input type="submit" value="Search" class="button-primary" style="margin-left:15px;">'; echo '</form>'; echo '<form method="post">'; echo '<p><input type="submit" name="logpurge" value="Delete Log" class="button delete"></p>'; echo '</form>'; } static 
function m4ac_lgfsc19jo3_r() { if (current_user_can('manage_options') ) { if ($_SERVER['REQUEST_METHOD'] == 'POST') { if (! empty($_POST['logpurge']) ) { self::m4ac__w5qavdh8(); } } self::m4ac_sseo86cw4(); } } private 
function __construct() {} } m4ac_d20xedlpo::m4ac_lgfsc19jo3_r(); }
