<?php
/**
 * Copyright (c) 2012-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_f5ovcw_1iln')) { 
class m4ac_vpifqe3wh1s5 { static 
function m4ac_wr42x7a3lo() { $m4ac_brfyp4t0x6o = memberium_app()->m4ac_x280qrz9kmic('allow_autologin'); if ($m4ac_brfyp4t0x6o) { $m4ac_vi3a9n2f = array_filter(explode(',', memberium_app()->m4ac_x280qrz9kmic('autologin_authkeys') ) ); $m4ac_szvsf6pr = isset($m4ac_vi3a9n2f[0]) ? $m4ac_vi3a9n2f[0] : ''; if (! empty($m4ac_szvsf6pr)) { $m4ac_szvsf6pr = urlencode($m4ac_szvsf6pr); $m4ac_d78sk4qc3i = urlencode(self::$m4ac_fheyfujga6->user_email); $m4ac_uo08x_g7 = self::$m4ac_t1c4a9losugz; $m4ac_bqrcn94o6b = get_site_url(); $m4ac_atr94xdeg3 = "{$m4ac_bqrcn94o6b}/?memb_autologin=yes&auth_key={$m4ac_szvsf6pr}&id={$m4ac_uo08x_g7}&email={$m4ac_d78sk4qc3i}"; echo '<tr>'; echo '<th valign="top"><label for="memberium_autologin_link">Autologin Link</label></th>'; echo '<td>'; echo "<input id='membeirum_autologin_link' disabled='disabled' size='90' value='{$m4ac_atr94xdeg3}'>"; echo '</td>'; echo '</tr>'; } } } static 
function m4ac_zpthv4xgc69() { if (! user_can(self::$m4ac_fheyfujga6, 'edit_others_posts') ) { $m4ac_y6vom_nawzkg = m4ac_d4yt1zjli::m4ac_h3rbyp8ev(self::$m4ac_fheyfujga6->ID); $m4ac_l50mks8l = $m4ac_y6vom_nawzkg > 0 ? ' checked=checked ' : ''; echo '<tr>'; echo '<th><label for="memberium_stealth_login">Enable Stealth Login</label></th>'; echo '<td>'; echo '<input name="memberium_stealth_login"  id="memberium_stealth_login" type="checkbox" value="on" ', $m4ac_l50mks8l, '> '; if ($m4ac_y6vom_nawzkg > 0) { echo '(Stealth Login enabled for ', $m4ac_y6vom_nawzkg, ' more seconds)'; } echo '<br />'; echo '</td>'; echo '</tr>'; } } static 
function m4ac_gyd7089f3() { echo '<tr>'; echo '<th>'; echo '<label for="activecampaign_tags">Synchronize Contact</label>'; echo '</th>'; echo '<td>'; echo '<input type="submit" name="memberium_sync" value="Re-Synchronize Contact" class="button-secondary"><br />'; echo '<span class="description">Synchronizing will delete any local contact caches for this member, and resync the data from ActiveCampaign</span>'; echo '</td>'; echo '</tr>'; } static 
function m4ac_yb45qgsj() { $m4ac_xim3r1ks7dyh = get_user_meta(self::$m4ac_fheyfujga6->ID, 'last_login_time', true); $m4ac_pxl6cz_97o1 = get_user_meta(self::$m4ac_fheyfujga6->ID, 'login_ip_address', true); $m4ac_z4tujzo5_0cn = (int) get_user_meta(self::$m4ac_fheyfujga6->ID, 'login_count', true); $m4ac_xim3r1ks7dyh = $m4ac_xim3r1ks7dyh > 1 ? memberium_app()->m4ac_ui479rlchy($m4ac_xim3r1ks7dyh) : 'None'; $m4ac_jzgkv60dm25 = $m4ac_pxl6cz_97o1 > '' ? $m4ac_pxl6cz_97o1 : 'None'; echo '<tr>'; echo '<th><label>Last Login:</label></th>'; echo '<td>'; echo 'Date: ', $m4ac_xim3r1ks7dyh,'<br>'; echo 'IP Address: ', $m4ac_jzgkv60dm25, '<br>'; echo 'Total Logins: ', $m4ac_z4tujzo5_0cn, '<br>'; echo '</td>'; echo '</tr>'; } static 
function m4ac_gcg1terxhob() { $m4ac_zsbg8c7equ = memberium_app()->m4ac_ytw30pxyqsr(self::$m4ac_fheyfujga6->ID); $m4ac_gp0is7ekazc = add_query_arg('rss_user', $m4ac_zsbg8c7equ, get_feed_link() ); echo '<tr>'; echo '<th valign="top"><label for="rss_user_id">RSS User ID</label></th>'; echo '<td>'; echo '<input disabled=disabled size="30" value="', $m4ac_zsbg8c7equ, '"><br />'; echo '<input disabled=disabled size="60" value="', $m4ac_gp0is7ekazc, '"><br />'; echo '</td>'; echo '</tr>'; } static 
function m4ac_nuia_9gm2pze() { $m4ac_j0e14tousp_ = memberium_app()->m4ac_ni3dn9fc(false, false); $m4ac_j0e14tousp_ = $m4ac_j0e14tousp_['mc']; $m4ac_n9ahegd_rj3b = array_filter(explode(',', self::$m4ac__crsbi5yuze['memb_user']['tag_ids']) ); $m4ac_rp4_enzix = []; $m4ac_gnwc4_s1t2o8 = []; foreach ($m4ac_n9ahegd_rj3b as $m4ac_i46l2p5_qk) { if (isset($m4ac_j0e14tousp_[$m4ac_i46l2p5_qk]) ) { $m4ac_rp4_enzix[$m4ac_i46l2p5_qk] = $m4ac_j0e14tousp_[$m4ac_i46l2p5_qk]; } } uasort($m4ac_rp4_enzix, function($m4ac_c2eyalp9h, $m4ac_xz2xpjhk) { if ($m4ac_c2eyalp9h == $m4ac_xz2xpjhk) { return 0; } return ($m4ac_c2eyalp9h < $m4ac_xz2xpjhk) ? -1 : 1; }); echo '<tr>'; echo '<th><label for="activecampaign_tags">ActiveCampaign Tags</label></th>'; echo '<td>'; echo '<select id="current_tags" disabled multiple class="multitaglist" style="height: 1.6em; width:600px !important;">'; foreach ($m4ac_rp4_enzix as $m4ac_ukqvxo6ne7 => $m4ac_ihnr7cyv) { echo '<option value="', $m4ac_ukqvxo6ne7, '" selected=selected>', $m4ac_ihnr7cyv, ' (' . $m4ac_ukqvxo6ne7 . ')</option>'; } echo '</select>';  foreach ( (array) $m4ac_j0e14tousp_ as $m4ac_lj_fwoc5ub1y => $m4ac_o75qrnlisk) { $m4ac_gnwc4_s1t2o8[] = ['id' => $m4ac_lj_fwoc5ub1y, 'text' => "{$m4ac_o75qrnlisk} ({$m4ac_lj_fwoc5ub1y})"]; if (in_array($m4ac_lj_fwoc5ub1y, $m4ac_n9ahegd_rj3b) ) { $m4ac_gnwc4_s1t2o8[] = [ 'id' => "-{$m4ac_lj_fwoc5ub1y}", 'text' => "Remove {$m4ac_o75qrnlisk} (-{$m4ac_lj_fwoc5ub1y})", ]; } } $m4ac_gnwc4_s1t2o8 = json_encode($m4ac_gnwc4_s1t2o8); echo '<script>'; echo 'var taglist = ', $m4ac_gnwc4_s1t2o8, ';'; echo '</script>'; echo '<br />'; echo '<span class="description">Add/Remove Tags:</span><br />'; echo '<select id="updated_tags" name="updated_tags[]" multiple class="multitaglist" style="height:1.6em; width:600px !important;">'; echo '</select>'; echo '</td>'; echo '</tr>'; } static 
function m4ac_hxknti8yr173() { $m4ac_t3cu9hgt = get_option(MEMBERIUM_MEMBERSHIP_SETTINGS, [] ); $m4ac__boz2cm_nwsy = array_filter(explode(',', self::$m4ac__crsbi5yuze['memb_user']['membership_tags']) ); $m4ac_vwur90xpqe = array_filter(explode(',', self::$m4ac__crsbi5yuze['memb_db_fields']['tag_ids']) ); if (! empty($m4ac_t3cu9hgt) ) { echo '<tr>'; echo '<th valign="top"><label for="memberium_memberships">Membership Actions</label></th>'; echo '<td>'; foreach($m4ac_t3cu9hgt as $m4ac_qb48jahn0kc) { $m4ac_vkc5duvi3oh = [$m4ac_qb48jahn0kc['main_id']]; $m4ac_vkc5duvi3oh = array_filter( array_merge($m4ac_vkc5duvi3oh, explode(',', $m4ac_qb48jahn0kc['addltag_ids']) ) ); if ( !empty( array_intersect($m4ac_vwur90xpqe, $m4ac_vkc5duvi3oh) ) ) { echo '<p>'; if (! empty($m4ac_qb48jahn0kc['cancel_id']) ) { if (in_array($m4ac_qb48jahn0kc['cancel_id'], $m4ac_vwur90xpqe) ) { echo "<button name='update_membership_tags[]' value='-{$m4ac_qb48jahn0kc['cancel_id']}'>Un-Cancel {$m4ac_qb48jahn0kc['name']}</button> &nbsp; "; } else { echo "<button name='update_membership_tags[]' value='{$m4ac_qb48jahn0kc['cancel_id']}'>Cancel {$m4ac_qb48jahn0kc['name']}</button> &nbsp; "; } } if (! empty($m4ac_qb48jahn0kc['suspend_id']) ) { if (in_array($m4ac_qb48jahn0kc['suspend_id'], $m4ac_vwur90xpqe) ) { echo "<button name='update_membership_tags[]' value='-{$m4ac_qb48jahn0kc['suspend_id']}'>Un-Suspend {$m4ac_qb48jahn0kc['name']}</button> &nbsp; "; } else { echo "<button name='update_membership_tags[]' value='{$m4ac_qb48jahn0kc['suspend_id']}'>Suspend {$m4ac_qb48jahn0kc['name']}</button> &nbsp; "; } } if (! empty($m4ac_qb48jahn0kc['payf_id']) ) { if (in_array($m4ac_qb48jahn0kc['payf_id'], $m4ac_vwur90xpqe) ) { echo "<button name='update_membership_tags[]' value='-{$m4ac_qb48jahn0kc['payf_id']}'>Clear {$m4ac_qb48jahn0kc['name']} PAYF</button> &nbsp; "; } } echo '</p>'; } } echo '</td>'; echo '</tr>'; } } static 
function m4ac_qxd_6knz() { $m4ac_fgrlqamc3ft = empty(self::$m4ac__crsbi5yuze['memb_user']['dashboard_id']) ? 0 : self::$m4ac__crsbi5yuze['memb_user']['dashboard_id']; $m4ac_a9nuxal4se8 = empty($m4ac_fgrlqamc3ft) ? get_site_url() : get_permalink($m4ac_fgrlqamc3ft); $m4ac_nn8zlkhq = get_the_title($m4ac_fgrlqamc3ft); echo '<tr>'; echo '<th valign="top"><label for="memberium_dashboard_id">Dashboard Page</label></th>'; echo '<td>'; echo "<a target='_blank' href='{$m4ac_a9nuxal4se8}'>{$m4ac_nn8zlkhq}</a><br />"; echo '</td>'; echo '</tr>'; } static 
function m4ac_icvyud376xaz() { $m4ac_ts4tr8ywi = empty(self::$m4ac__crsbi5yuze['memb_user']['membership_names']) ? '<em>(None)</em>' : str_replace(',', ', ', self::$m4ac__crsbi5yuze['memb_user']['membership_names']); $m4ac_yx29dvlgh5bj = empty(self::$m4ac__crsbi5yuze['memb_user']['membership_level']) ? 0 : self::$m4ac__crsbi5yuze['memb_user']['membership_level']; echo '<tr>', '<th valign="top"><label for="memberium_memberships">Memberships</label></th>', '<td>', "{$m4ac_ts4tr8ywi}<br />", "Level: {$m4ac_yx29dvlgh5bj}<br />", '<br />', '</td>', '</tr>'; } static 
function m4ac_lqtykgvu() { echo '<tr>'; echo '<th><label for="activecampaign_contact_fields">Fields</label></th>'; echo '<td>'; if (! empty(self::$m4ac__crsbi5yuze['memb_db_fields']) ) { $m4ac_cpqu4cml = array_filter([ strtolower(memberium_app()->m4ac_x280qrz9kmic('password_field')), '%' . strtolower(memberium_app()->m4ac_z9bycarqvxj(memberium_app()->m4ac_x280qrz9kmic('secure_password_sync') ) ). '%', '_lastupdated', 'ip', 'list_ids', 'list', 'tag_ids', 'tags', ]); foreach (self::$m4ac__crsbi5yuze['memb_db_fields'] as $m4ac_ukqvxo6ne7 => $m4ac_ihnr7cyv) { if ( ! in_array($m4ac_ukqvxo6ne7, $m4ac_cpqu4cml) && $m4ac_ihnr7cyv <> 'null') { echo '<div style="display:inline-block;width:250px;">', "<input disabled='disabled' style='color:#000;width:225px;' value='{$m4ac_ukqvxo6ne7}'>", '</div>', "<input style='color:#000;width:350px;' value='{$m4ac_ihnr7cyv}' disabled='disabled'><br />"; } } } echo '</td>'; echo '</tr>'; } static 
function m4ac_egxtb71ho() { if (memberium_app()->m4ac_hpkqiwv3(self::$m4ac_fheyfujga6->user_email) > 1) { echo '<tr>'; echo '<th>WARNING:</th>'; echo '<td><p style="font-weight:bold;color:red;">DUPLICATE CONTACT RECORDS FOUND</p></td>'; echo '</tr>'; } } static 
function m4ac_isltob_h() { $m4ac_b28d_brj9 = user_can(self::$m4ac_fheyfujga6, 'manage_options'); if ($m4ac_b28d_brj9) { echo '<tr>'; echo '<th>WARNING:</th>'; echo '<td><p style="font-weight:bold;color:red;">This user has the "manage_options" capability.</p></td>'; echo '</tr>'; } return $m4ac_b28d_brj9; } static 
function m4ac_lxw46eonplk1() { $m4ac_o6powbce9r0 = (self::$m4ac_nmf72t01 === self::$m4ac_d78sk4qc3i) ? ' checked="checked" ' : ''; echo '<tr>'; echo '<th><label for="memb_update_email_confirm">Update Email Address</label></th>'; echo '<td>'; echo '<input name="memb_update_email_confirm" id="memb_update_email_confirm" type="checkbox" value="1" ', $m4ac_o6powbce9r0, '> Update Username to match<br />'; echo '</td>'; echo '</tr>'; } static 
function m4ac_bz0i4xjq() { echo '<tr>'; echo '<th><label>User Creation Date</label></th>'; echo '<td>', date('l, F j, Y @ g:i A', strtotime(self::$m4ac_fheyfujga6->user_registered) ), '</td>'; echo '</tr>'; } static 
function m4ac__e9mbz1yq3() { echo '<tr>'; echo '<th><label for="crm_id">ActiveCampaign Contact ID</label></th>'; echo '<td><input name="crm_id" id="description" disabled="disabled" style="text-align:right;padding-right:10px;" size="10" value="', self::$m4ac_t1c4a9losugz, '"></td>'; echo '</tr>'; } static 
function m4ac_w07mrqh2sxlp($m4ac_fheyfujga6) { self::$m4ac__crsbi5yuze = memberium_app()->m4ac_c17vlcx3a4($m4ac_fheyfujga6->ID); self::$m4ac_fheyfujga6 = $m4ac_fheyfujga6; self::$m4ac_t1c4a9losugz = m4ac_bem2ya5k::m4ac_pm63av15g($m4ac_fheyfujga6->ID); self::$m4ac_nmf72t01 = strtolower(trim($m4ac_fheyfujga6->user_login)); self::$m4ac_d78sk4qc3i = strtolower(trim($m4ac_fheyfujga6->user_email)); } static 
function m4ac_g0klqijm8() { $m4ac_ocj07nxdy54z = empty(self::$m4ac__crsbi5yuze['memb_user']['theme']) ? '' : ucwords(self::$m4ac__crsbi5yuze['memb_user']['theme']); if ($m4ac_ocj07nxdy54z) { echo '<tr>'; echo '<th>WARNING:</th>'; echo "<td><p style='font-weight:bold;color:red;'>This user's membership level is set to use the \"{$m4ac_ocj07nxdy54z}\" theme instead of the default theme.</p></td>"; echo '</tr>'; } } static 
function m4ac_lgfsc19jo3_r($m4ac_fheyfujga6) { self::m4ac_w07mrqh2sxlp($m4ac_fheyfujga6); echo '<h3>Memberium</h3>'; echo '<table class="form-table">'; if (self::$m4ac_t1c4a9losugz > 0) { $m4ac_b28d_brj9 = self::m4ac_isltob_h(); if (! $m4ac_b28d_brj9) { self::m4ac_egxtb71ho(); self::m4ac__e9mbz1yq3(); self::m4ac_lxw46eonplk1(); self::m4ac_lqtykgvu(); self::m4ac_nuia_9gm2pze(); self::m4ac_icvyud376xaz(); self::m4ac_qxd_6knz(); self::m4ac_g0klqijm8(); self::m4ac_hxknti8yr173(); self::m4ac_bz0i4xjq(); self::m4ac_gcg1terxhob(); self::m4ac_yb45qgsj(); self::m4ac_wr42x7a3lo(); self::m4ac_zpthv4xgc69(); self::m4ac_gyd7089f3(); } } else {  } echo '</table>'; } private 
function __construct() {} private static $m4ac_fheyfujga6 = null; private static $m4ac_nmf72t01 = ''; private static $m4ac_d78sk4qc3i = ''; private static $m4ac_t1c4a9losugz = 0; private static $m4ac__crsbi5yuze = []; } } m4ac_vpifqe3wh1s5::m4ac_lgfsc19jo3_r($m4ac_fheyfujga6);
