<?php
/**
 * Copyright (c) 2020-2021 David J Bullock
 * Web Power and Light
 */

 if (class_exists('m4ac_c6rqypiacz4') ) { final 
class m4ac_gtok6ui9 {    
function m4ac_joch_re68k($m4ac_qz2fsdy3pb = []) { $m4ac_cq4ed9naz7 = [ 'achievement-type', 'badgeos-log-entry', 'badges', 'nomination', 'step', 'submission', ]; $m4ac_o_wlyfigm97c = $this->m4ac_bqr_kovh(); return array_merge($m4ac_qz2fsdy3pb, $m4ac_cq4ed9naz7, $m4ac_o_wlyfigm97c); } 
function m4ac_bqr_kovh() { global $wpdb; static $m4ac_id7k9t2q = []; if (empty($m4ac_id7k9t2q) ) { $m4ac_xtcz6bi97flk = "SELECT LOWER(`post_name`) FROM `{$wpdb->posts}` WHERE `post_type` = 'achievement-type' AND `post_status` = 'publish'"; $m4ac_f92tkhgnzfcb = $wpdb->get_col($m4ac_xtcz6bi97flk, 0); $m4ac_id7k9t2q = is_array($m4ac_f92tkhgnzfcb) ? $m4ac_f92tkhgnzfcb : $m4ac_id7k9t2q; } return $m4ac_id7k9t2q; } private 
function m4ac_lr9hmjnp587u() { global $wpdb; $m4ac_o_wlyfigm97c = [];  $m4ac_xtcz6bi97flk = "SELECT `ID` as `id`, `post_title` as `name` FROM `{$wpdb->posts}` WHERE `post_status` = 'publish' AND `post_type` IN (SELECT `post_name` FROM `{$wpdb->posts}` WHERE `post_type` = 'achievement-type' AND `post_status` = 'publish'); "; $rows = $wpdb->get_results($m4ac_xtcz6bi97flk, ARRAY_A); foreach ($rows as $row) { $m4ac_o_wlyfigm97c[$row['id']] = $row['name']; } return $m4ac_o_wlyfigm97c; } private 
function m4ac_dyqukh75g() { $m4ac_uvbwy6m8tqzj = $this->m4ac_bqr_kovh(); $m4ac_ah90o86m = [ 'numberposts' => -1, 'order' => 'ASC', 'orderby' => 'ID', 'post_status' => 'publish', 'post_type' => $m4ac_uvbwy6m8tqzj, 'fields' => 'ids', ]; $m4ac_lel0isn7jtkw = get_posts($m4ac_ah90o86m); $m4ac_ckfu62mpdy = []; foreach($m4ac_lel0isn7jtkw as $m4ac_lj_fwoc5ub1y) { $m4ac_o75qrnlisk = get_post_meta($m4ac_lj_fwoc5ub1y, '_memberium_badgeos_badge_add', true); if ($m4ac_o75qrnlisk) { $m4ac_ckfu62mpdy[$m4ac_lj_fwoc5ub1y] = $m4ac_o75qrnlisk; } } update_option('memberium/badgeos/assign_by_tag', $m4ac_ckfu62mpdy, false); $m4ac_ckfu62mpdy = []; foreach($m4ac_lel0isn7jtkw as $m4ac_lj_fwoc5ub1y) { $m4ac_o75qrnlisk = get_post_meta($m4ac_lj_fwoc5ub1y, '_memberium_badgeos_tag_add', true); if ($m4ac_o75qrnlisk) { $m4ac_ckfu62mpdy[$m4ac_lj_fwoc5ub1y] = $m4ac_o75qrnlisk; } } update_option('memberium/badgeos/tag_by_badge', $m4ac_ckfu62mpdy, false); } private 
function m4ac_gm6_pd7vl() { return [ '_memberium_badgeos_badge_add', '_memberium_badgeos_tag_add', '_memberium_lms_achievement', ]; }    
function m4ac_ntcus0hd() { $m4ac_dxtjcmeridh = m4ac_s126v0fexga::m4ac_udme4nbtp(); $m4ac_uvbwy6m8tqzj = $this->m4ac_bqr_kovh(); $m4ac_mmo1k6z98cfp = in_array($m4ac_dxtjcmeridh, $m4ac_uvbwy6m8tqzj); $m4ac_jnf5st6j4vi = in_array($m4ac_dxtjcmeridh, apply_filters('memberium/lms/module_post_types', []) ); if ($m4ac_mmo1k6z98cfp) { add_meta_box('memberium-badgeos-achievements', 'BadgeOS for Memberium', [$this, 'm4ac_pljf5peh'], $m4ac_dxtjcmeridh, 'side'); } if ($m4ac_jnf5st6j4vi) { $m4ac__i4nlxz98k5y = apply_filters('memberium/lms/name', 'LMS'); add_meta_box( 'memberium-lms-achievements', "BadgeOS for {$m4ac__i4nlxz98k5y}", [$this, 'm4ac_kqplm84tnkv'], $m4ac_dxtjcmeridh, 'side' ); } add_action('save_post', [$this, 'm4ac_b0qd9cuhwf']); } 
function m4ac_pljf5peh() { global $post; $m4ac_x16i5xouf = get_post_meta($post->ID, '_memberium_badgeos_badge_add', true); $m4ac_wftei15bzn0x = get_post_meta($post->ID, '_memberium_badgeos_tag_add', true); wp_nonce_field(__CLASS__, "memberium/badgeos/metabox/achievement/{$post->ID}"); echo '<label for="_memberium_badgeos_badge_add">', _e("Add Badge if Member has Tag", 'memberium'), ':</label> '; echo '<input name="_memberium_badgeos_badge_add" class="tag-selector" style="width:100%; max-width:100%" value="', (empty($m4ac_x16i5xouf) ? 0 : $m4ac_x16i5xouf), '"><br /><br />'; echo '<label for="_memberium_badgeos_tag_add">', _e("Add Tag if Member has Badge", 'memberium'), ':</label> '; echo '<input name="_memberium_badgeos_tag_add" class="tag-selector" style="width:100%; max-width:100%" value="', (empty($m4ac_wftei15bzn0x) ? 0 : $m4ac_wftei15bzn0x), '"><br /><br />'; do_action('memberium/badgeos/achievement_metabox'); memberium_app()->m4ac_dfujoe3avi_()->m4ac_iy1htpsfj(); } 
function m4ac_b0qd9cuhwf($m4ac__37l6rhivt2) { if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) { return; } if (! current_user_can('edit_posts', $m4ac__37l6rhivt2) ) { return; } if (empty($_POST["memberium/badgeos/metabox/achievement/{$m4ac__37l6rhivt2}"]) || ! wp_verify_nonce($_POST["memberium/badgeos/metabox/achievement/{$m4ac__37l6rhivt2}"], __CLASS__) ) { return; } memberium_app()->m4ac_wq7u84xw5v0($m4ac__37l6rhivt2, $this->m4ac_gm6_pd7vl() ); $this->m4ac_dyqukh75g(); } 
function m4ac_kqplm84tnkv() { global $post; $m4ac_ukqvxo6ne7 = '_memberium_lms_achievement'; $m4ac_xurp0xnols83 = get_post_meta($post->ID, $m4ac_ukqvxo6ne7, true); $m4ac_xurp0xnols83 = empty($m4ac_xurp0xnols83) ? 0 : $m4ac_xurp0xnols83; $m4ac_o_wlyfigm97c = $this->m4ac_lr9hmjnp587u(); $m4ac_s2acj3pxehq = get_post_type_object($post->post_type)->labels->singular_name; wp_nonce_field(__CLASS__, "memberium_badgeos_lms_nonce_{$post->ID}"); echo "<label for='{$m4ac_ukqvxo6ne7}'>", _e('Add Badge on Completion of ', 'memberium'), "{$m4ac_s2acj3pxehq}:</label> "; echo '<select class="actionset-selector" name="', $m4ac_ukqvxo6ne7, '" style="width:100%; max-width:100%">'; echo '<option value="0">(No Achievement)</option>'; if (is_array($m4ac_o_wlyfigm97c)) { foreach ($m4ac_o_wlyfigm97c as $m4ac_lj_fwoc5ub1y => $m4ac_pzocy3nw) { $m4ac_x2yxklc6q3_p = ($m4ac_xurp0xnols83 == $m4ac_lj_fwoc5ub1y) ? ' selected="selected" ' : ''; echo "<option value='{$m4ac_lj_fwoc5ub1y}' {$m4ac_x2yxklc6q3_p}>{$m4ac_pzocy3nw}</option>"; } } echo '</select>'; echo '<br /><br />'; do_action('memberium/badgeos/achievement_metabox'); } 
function m4ac_x3t1pbg2wmqv($m4ac__37l6rhivt2, $m4ac_maz5nvkp, $m4ac_jtf3bjyul2d) {  if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) { return; }  if (empty($_POST["memberium_badgeos_lms_nonce_{$m4ac__37l6rhivt2}"]) || ! wp_verify_nonce($_POST["memberium_badgeos_lms_nonce_{$m4ac__37l6rhivt2}"], __CLASS__) ) { return; } if (! current_user_can('edit_posts', $m4ac__37l6rhivt2) ) { return; } memberium_app()->m4ac_wq7u84xw5v0($m4ac__37l6rhivt2, $this->m4ac_gm6_pd7vl() ); }    
function m4ac_sj9nudr1() { $this->m4ac_ntcus0hd(); } 
function m4ac_rh6ijntd() { add_action('admin_init', [$this, 'm4ac_sj9nudr1']); add_filter('memberium/unenhanced_posts', [$this, 'm4ac_joch_re68k'], 10, 1); } private 
function __construct() { $this->m4ac_rh6ijntd(); } static 
function m4ac_zw_dhmca() { static $m4ac_u4tpxcro19 = false; return $m4ac_u4tpxcro19 ? $m4ac_u4tpxcro19 : $m4ac_u4tpxcro19 = new self; } } }
