<?php
 if (class_exists('m4ac_c6rqypiacz4') ) { 
class m4ac_ght6_dfuw87 { 
function m4ac_h3bku5xcy( $m4ac_qsvd0m6oq, $m4ac_fheyfujga6 ) { if ( is_a($m4ac_fheyfujga6, 'WP_User') ) { $m4ac_at_5xofh = $m4ac_fheyfujga6->ID; if ( function_exists('bp_xprofile_firstname_field_id') && function_exists('bp_xprofile_lastname_field_id') ) { $m4ac_f904cf17pih8 = bp_xprofile_firstname_field_id(); $m4ac_d1b_rlw2es = bp_xprofile_lastname_field_id(); $m4ac_b0hw9pif_qj = empty($_POST["field_{$m4ac_f904cf17pih8}"]) ? '' : $_POST["field_{$m4ac_f904cf17pih8}"]; $m4ac_ce5wvyafjo = empty($_POST["field_{$m4ac_d1b_rlw2es}"]) ? '' : $_POST["field_{$m4ac_d1b_rlw2es}"]; $m4ac_qsvd0m6oq['firstname'] = empty($m4ac_qsvd0m6oq['firstname']) ? $m4ac_b0hw9pif_qj : $m4ac_qsvd0m6oq['firstname']; $m4ac_qsvd0m6oq['lastname'] = empty($m4ac_qsvd0m6oq['lastname']) ? $m4ac_ce5wvyafjo : $m4ac_qsvd0m6oq['lastname']; } else { $m4ac_ner21xt_gh0y = array_filter( explode( ',', $_POST['signup_profile_field_ids'] ) ); $m4ac_a9gw15htk = [ 'Name' => 'firstname', 'Last Name' => 'lastname', 'Company' => 'organization', ]; foreach($m4ac_ner21xt_gh0y as $m4ac_uxtpu8skb) { $m4ac_wc9s2dnt4y = BP_XProfile_Field::get_instance($m4ac_uxtpu8skb); $m4ac_woab9rpxw = property_exists($m4ac_wc9s2dnt4y, 'name') ? $m4ac_wc9s2dnt4y->name : ''; if ( ! empty($m4ac_woab9rpxw) && array_key_exists($m4ac_woab9rpxw, $m4ac_a9gw15htk) ) { $m4ac_rvzd0gjwx561 = isset($m4ac_a9gw15htk[$m4ac_woab9rpxw]) ? $m4ac_a9gw15htk[$m4ac_woab9rpxw] : ''; $m4ac_r9mqvu4gzs7f = "field_{$m4ac_uxtpu8skb}"; if (! empty($m4ac_rvzd0gjwx561) && ! empty( $_POST[$m4ac_r9mqvu4gzs7f] ) ) { $m4ac_qsvd0m6oq[$m4ac_rvzd0gjwx561] = $_POST[$m4ac_r9mqvu4gzs7f]; } } }  } } return $m4ac_qsvd0m6oq; } 
function m4ac_j5a26_30dtfg( $m4ac_at_5xofh ) { $m4ac_fheyfujga6 = get_user_by('id', $m4ac_at_5xofh); if ( is_a( $m4ac_fheyfujga6, 'WP_User' ) ) { $m4ac_y6n73tb0c5 = $m4ac_fheyfujga6->user_login; $m4ac_dsbyx4fkre = new BP_Signup; $m4ac_md7c8zsu2o = $m4ac_dsbyx4fkre->get( ['user_login' => $m4ac_y6n73tb0c5] ); $m4ac_tu6fnt4bj = isset( $m4ac_md7c8zsu2o['signups'][0]->signup_id ) ? $m4ac_md7c8zsu2o['signups'][0]->signup_id : 0; if ($m4ac_tu6fnt4bj) { $m4ac_dsbyx4fkre->activate([$m4ac_tu6fnt4bj]); } } } 
function m4ac__hjrz4kb53() { remove_filter('login_redirect', 'buddyboss_redirect_previous_page', 10); } 
function m4ac_y2hj8ioyuefn($m4ac_upwqy_51nxj) { foreach($m4ac_upwqy_51nxj as $m4ac_lj_fwoc5ub1y => $m4ac_kkbmiyjr7p2) { $m4ac_hl6gy301h_ = BP_XProfile_Field::get_instance($m4ac_lj_fwoc5ub1y); if (empty($m4ac_hl6gy301h_->id)) { unset($m4ac_upwqy_51nxj[$m4ac_lj_fwoc5ub1y]); } } $this->m4ac_wb5mgd_ka = $m4ac_upwqy_51nxj; update_option('memberium/buddypress/xprofile/map', $m4ac_upwqy_51nxj, false); } 
function m4ac_bpj9gib0t() { if ($this->m4ac_wb5mgd_ka === false) { $this->m4ac_wb5mgd_ka = get_option('memberium/buddypress/xprofile/map', []); } return $this->m4ac_wb5mgd_ka; } 
function m4ac_b37_vfdj($m4ac_at_5xofh, $m4ac_upwqy_51nxj) { global $wpdb; $m4ac_e3ht7j0fxgiq = []; if (! empty($m4ac_at_5xofh) && ! empty($m4ac_upwqy_51nxj) ) { $m4ac_ks5fpk_lrjmz = "'" . implode("', '", $m4ac_upwqy_51nxj) . "'"; $m4ac_jbqpi7nfo48 = 'memb\_%'; $m4ac_xtcz6bi97flk = "SELECT `meta_key`, `meta_value` FROM {$wpdb->usermeta} WHERE `user_id` = {$m4ac_at_5xofh} AND (`meta_key` LIKE '{$m4ac_jbqpi7nfo48}' OR `meta_key` IN ( {$m4ac_ks5fpk_lrjmz} ) ); "; $m4ac_x_1sx47rpefc = $wpdb->get_results( $m4ac_xtcz6bi97flk, ARRAY_A); if (! empty($m4ac_x_1sx47rpefc) && is_array($m4ac_x_1sx47rpefc)) { foreach($m4ac_x_1sx47rpefc as $m4ac_usct73fd9gm) { $m4ac_ukqvxo6ne7 = $m4ac_usct73fd9gm['meta_key']; if (in_array($m4ac_ukqvxo6ne7, $m4ac_upwqy_51nxj) ) { $m4ac_ihnr7cyv = $m4ac_usct73fd9gm['meta_value']; $m4ac_e3ht7j0fxgiq[$m4ac_ukqvxo6ne7] = $m4ac_ihnr7cyv; } } } } return $m4ac_e3ht7j0fxgiq; } 
function m4ac_u9iwesd7g($m4ac_at_5xofh, $m4ac__5168racihv, $m4ac_f_1orakx, $m4ac_mwxbjz1po, $m4ac_rswfo5d60ipq) { foreach($m4ac_rswfo5d60ipq as $m4ac_vg5aicnk40 => $m4ac_md7c8zsu2o) { if ($m4ac_md7c8zsu2o['value'] == $m4ac_mwxbjz1po[$m4ac_vg5aicnk40]['value']) { unset($m4ac_rswfo5d60ipq[$m4ac_vg5aicnk40]); } } if (! empty($m4ac_rswfo5d60ipq)) { $m4ac_a9gw15htk = $this->m4ac_bpj9gib0t(); $m4ac_gin7btw5 = $this->m4ac_b37_vfdj($m4ac_at_5xofh, $m4ac_a9gw15htk); $m4ac_ri4g59oc_0 = []; foreach($m4ac_rswfo5d60ipq as $m4ac_vg5aicnk40 => $m4ac_md7c8zsu2o) { if ($m4ac_md7c8zsu2o['value'] <> $m4ac_mwxbjz1po[$m4ac_vg5aicnk40]['value']) { if (isset($m4ac_a9gw15htk[$m4ac_vg5aicnk40])) { $m4ac_go2gtisry = $m4ac_a9gw15htk[$m4ac_vg5aicnk40]; if ($m4ac_gin7btw5[$m4ac_go2gtisry] <> $m4ac_md7c8zsu2o['value']) { update_user_meta($m4ac_at_5xofh, $m4ac_go2gtisry, $m4ac_md7c8zsu2o['value']);; } } } } } } 
function m4ac_zodpxjib2($m4ac_b69obly_uf, $m4ac_at_5xofh, $m4ac_jj79h_ou1vm, $m4ac_j2lrxtga, $m4ac_htwp87cb = '') { if ($m4ac_htwp87cb == $m4ac_j2lrxtga) { return; } if (function_exists( 'xprofile_get_field_data' ) && function_exists( 'xprofile_set_field_data' ) ) { $m4ac_upwqy_51nxj = array_flip($this->m4ac_bpj9gib0t() ); if (! array_key_exists($m4ac_jj79h_ou1vm, $m4ac_upwqy_51nxj)) { return; } $m4ac_d5x_oyrt4d = $m4ac_upwqy_51nxj[$m4ac_jj79h_ou1vm]; $m4ac_e_y7fg12h = xprofile_get_field_data($m4ac_d5x_oyrt4d, $m4ac_at_5xofh); if ($m4ac_e_y7fg12h == $m4ac_j2lrxtga) { return; } $m4ac_fic2e07vfkz = xprofile_set_field_data($m4ac_d5x_oyrt4d, $m4ac_at_5xofh, $m4ac_j2lrxtga); } } 
function m4ac_g08zk_1ojp(int $m4ac_at_5xofh, array $m4ac__crsbi5yuze) { if (function_exists('bp_set_member_type') && function_exists('bp_get_member_type') ) { $m4ac_h7_6lgxef = isset($m4ac__crsbi5yuze['memb_user']['membership_id']) ? $m4ac__crsbi5yuze['memb_user']['membership_id'] : ''; $m4ac_ewvlruxkj2 = bp_get_member_type($m4ac_at_5xofh); if ($m4ac_h7_6lgxef) { $m4ac_qb48jahn0kc = get_option(MEMBERIUM_MEMBERSHIP_SETTINGS, [] )[$m4ac_h7_6lgxef]; if (! empty($m4ac_qb48jahn0kc['buddypress_profile_type'])) { $m4ac_op54z30n6xgs = $m4ac_qb48jahn0kc['buddypress_profile_type']; if ($m4ac_op54z30n6xgs !== $m4ac_ewvlruxkj2) { bp_set_member_type($m4ac_at_5xofh, $m4ac_op54z30n6xgs); } } } } } 
function m4ac_zef6jv394kb() { if (bp_is_active('groups') ) { if (class_exists('BP_Groups_Group') && class_exists('BP_Group_Extension') ) { require __DIR__ . '/groups.php'; m4ac_eltp7eu4f::m4ac_zw_dhmca(); if (is_admin() ) { if (function_exists( 'bp_register_group_extension' ) ) { require_once __DIR__ . '/groups_admin.php'; bp_register_group_extension('m4ac_c58gum1h3fp'); } } } } } 
function m4ac_k5s3er67yvc8(int $m4ac_at_5xofh, array $m4ac__crsbi5yuze) { update_user_meta($m4ac_at_5xofh, 'memberium/buddypress/access/updated', time() ); $this->m4ac_n12tprzqhl[$m4ac_at_5xofh] = $m4ac__crsbi5yuze; } 
function m4ac_jw39xlcjk() { return $this->m4ac_n12tprzqhl; } private 
function m4ac_rh6ijntd() { add_action('update_user_meta', [$this, 'm4ac_zodpxjib2'], 20, 5); add_action('xprofile_updated_profile', [$this, 'm4ac_u9iwesd7g'], 0, 5); add_action('memberium/session/updated', [$this, 'm4ac_g08zk_1ojp'], 10, 2); add_action('memberium/session/updated', [$this, 'm4ac_k5s3er67yvc8'], PHP_INT_MAX, 2); add_action('after_setup_theme', [$this, 'm4ac__hjrz4kb53']); add_action('bp_include', [$this, 'm4ac_zef6jv394kb']); add_filter( 'memberium/user/register/fields', [$this, 'm4ac_h3bku5xcy'], 99, 2 ); if (is_admin() ) { include_once __DIR__ . '/admin.php'; m4ac_kcy5l6erqaot::m4ac_zw_dhmca(); } else { include_once __DIR__ . '/frontend.php'; m4ac_okn1hzlf9::m4ac_zw_dhmca(); } } private 
function __construct() { $this->m4ac_rh6ijntd(); } static 
function m4ac_zw_dhmca() : self { static $m4ac_u4tpxcro19 = false; return $m4ac_u4tpxcro19 ? $m4ac_u4tpxcro19 : $m4ac_u4tpxcro19 = new self; } private $m4ac_wb5mgd_ka = false; private $m4ac_n12tprzqhl = []; } }
